import { FormEvent, useEffect, useState } from 'react';
import { Cable, CheckCircle2, CloudDownload, Link2, RefreshCw, ShieldCheck, Unplug } from 'lucide-react';
import { supabase } from './lib/supabase';
import AdminTrackingConfig from './AdminTrackingConfig';
import './growth-connections.css';

type Connection={provider:string;status:string;account_id?:string|null;account_name?:string|null;last_sync_at?:string|null;last_error?:string|null};
type Campaign={id:string;name:string;platform:string;external_campaign_id?:string|null;provider_sync_enabled?:boolean;max_daily_budget?:number|null};

const providerLabel=(p:string)=>p==='google_ads'?'Google Ads':'Meta Ads';
const platformProvider=(p:string)=>['google_search','google_display','youtube'].includes(p)?'google_ads':['meta','facebook','instagram'].includes(p)?'meta_ads':null;

export default function AdminGrowthConnections(){
 const[connections,setConnections]=useState<Connection[]>([]);const[campaigns,setCampaigns]=useState<Campaign[]>([]);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');
 useEffect(()=>{load()},[]);
 async function load(){if(!supabase)return;setBusy(true);const[c,p]=await Promise.all([supabase.from('marketing_provider_connections').select('*').order('provider'),supabase.from('marketing_campaigns').select('id,name,platform,external_campaign_id,provider_sync_enabled,max_daily_budget').order('created_at')]);setConnections((c.data||[]) as Connection[]);setCampaigns((p.data||[]) as Campaign[]);setBusy(false)}
 async function connectGoogle(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);setMsg('');const f=new FormData(e.currentTarget);const{data,error}=await supabase.functions.invoke('configure-growth-provider',{body:{provider:'google_ads',client_id:String(f.get('client_id')||''),client_secret:String(f.get('client_secret')||''),refresh_token:String(f.get('refresh_token')||''),developer_token:String(f.get('developer_token')||''),customer_id:String(f.get('customer_id')||''),login_customer_id:String(f.get('login_customer_id')||'')}});setMsg(error||!data?.ok?`Google Ads não conectado: ${data?.error||error?.message||'falha de validação'}.`:`Google Ads conectado à conta ${data.account_id}.`);if(data?.ok)(e.currentTarget as HTMLFormElement).reset();await load();setBusy(false)}
 async function connectMeta(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);setMsg('');const f=new FormData(e.currentTarget);const{data,error}=await supabase.functions.invoke('configure-growth-provider',{body:{provider:'meta_ads',access_token:String(f.get('access_token')||''),ad_account_id:String(f.get('ad_account_id')||'')}});setMsg(error||!data?.ok?`Meta Ads não conectado: ${data?.error||error?.message||'falha de validação'}.`:`Meta Ads conectado${data.account_name?` — ${data.account_name}`:''}.`);if(data?.ok)(e.currentTarget as HTMLFormElement).reset();await load();setBusy(false)}
 async function linkCampaign(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget);const id=String(f.get('campaign_id')||''),external=String(f.get('external_campaign_id')||'').trim(),max=String(f.get('max_daily_budget')||'');if(!id||!external)return;setBusy(true);const{error}=await supabase.from('marketing_campaigns').update({external_campaign_id:external,provider_sync_enabled:true,max_daily_budget:max?Number(max):null}).eq('id',id);setMsg(error?'Não foi possível vincular a campanha.':'Campanha vinculada. A próxima sincronização buscará dados reais da plataforma.');if(!error)(e.currentTarget as HTMLFormElement).reset();await load();setBusy(false)}
 async function toggleSync(c:Campaign){if(!supabase)return;await supabase.from('marketing_campaigns').update({provider_sync_enabled:!c.provider_sync_enabled}).eq('id',c.id);await load()}
 async function sync(apply:boolean){if(!supabase)return;setBusy(true);setMsg(apply?'Sincronizando e executando regras autorizadas...':'Sincronizando métricas das plataformas...');const{data,error}=await supabase.functions.invoke('growth-sync',{body:{apply_optimization:apply}});if(error||!data?.ok)setMsg(`Falha na sincronização: ${data?.detail||data?.error||error?.message||'erro desconhecido'}.`);else{const ok=(data.synced||[]).filter((x:any)=>x.ok).length;const fail=(data.synced||[]).filter((x:any)=>!x.ok).length;setMsg(`Sincronização concluída: ${ok} campanha(s) atualizada(s)${fail?` • ${fail} com erro`:''}.${apply?` ${data.optimization?.actions_applied||0} ação(ões) internas aplicada(s).`:''}`)}await load();setBusy(false)}
 const get=(p:string)=>connections.find(c=>c.provider===p);
 const linked=campaigns.filter(c=>c.external_campaign_id);
 return <><AdminTrackingConfig/><section className="admin-panel growth-connect"><div className="panel-title"><div><small>CONEXÕES DE MÍDIA</small><h2><Cable/> Motor conectado às plataformas</h2><p>Credenciais ficam no cofre seguro do backend. O navegador nunca recebe tokens gravados.</p></div><button className="secondary-admin" onClick={load} disabled={busy}><RefreshCw className={busy?'spin':''}/> Atualizar</button></div>
 <div className="provider-grid">{['google_ads','meta_ads'].map(p=>{const c=get(p);return <article className={`provider-card ${c?.status||'disconnected'}`} key={p}><div><span className="provider-icon">{c?.status==='connected'?<CheckCircle2/>:<Unplug/>}</span><div><strong>{providerLabel(p)}</strong><small>{c?.status==='connected'?(c.account_name||c.account_id||'Conectado'):'Ainda não conectado'}</small></div></div>{c?.last_sync_at&&<small>Última sincronização: {new Date(c.last_sync_at).toLocaleString('pt-BR')}</small>}{c?.last_error&&<em>{c.last_error}</em>}</article>})}</div>
 <div className="connector-forms"><form onSubmit={connectGoogle}><h3>Conectar Google Ads</h3><p>Use credenciais OAuth e o Developer Token da conta autorizada.</p><label>Client ID<input name="client_id" autoComplete="off" required/></label><label>Client Secret<input name="client_secret" type="password" autoComplete="new-password" required/></label><label>Refresh Token<input name="refresh_token" type="password" autoComplete="new-password" required/></label><label>Developer Token<input name="developer_token" type="password" autoComplete="new-password" required/></label><label>Customer ID<input name="customer_id" placeholder="123-456-7890" required/></label><label>Login Customer ID <small>opcional, para conta gerente</small><input name="login_customer_id" placeholder="123-456-7890"/></label><button disabled={busy}><ShieldCheck/> Validar e conectar</button></form>
 <form onSubmit={connectMeta}><h3>Conectar Meta Ads</h3><p>Informe a conta de anúncios e um token autorizado para leitura de Insights.</p><label>Access Token<input name="access_token" type="password" autoComplete="new-password" required/></label><label>Ad Account ID<input name="ad_account_id" placeholder="act_123456789 ou 123456789" required/></label><button disabled={busy}><ShieldCheck/> Validar e conectar</button></form></div>
 <div className="campaign-linker"><div><small>MAPEAMENTO</small><h3><Link2/> Vincular campanha real</h3><p>Associe cada campanha planejada ao ID da campanha existente no Google Ads ou Meta Ads. Nada é publicado automaticamente nesta etapa.</p></div><form onSubmit={linkCampaign}><label>Campanha<select name="campaign_id" required><option value="">Selecione</option>{campaigns.filter(c=>platformProvider(c.platform)).map(c=><option value={c.id} key={c.id}>{c.name} • {providerLabel(platformProvider(c.platform)!)}</option>)}</select></label><label>ID externo<input name="external_campaign_id" placeholder="ID da campanha na plataforma" required/></label><label>Teto de verba/dia<input name="max_daily_budget" type="number" min="0" step="0.01" placeholder="Ex.: 100"/></label><button disabled={busy}>Vincular e sincronizar</button></form></div>
 {linked.length>0&&<div className="linked-campaigns"><h3>Campanhas conectadas</h3>{linked.map(c=><article key={c.id}><div><b>{c.name}</b><small>{providerLabel(platformProvider(c.platform)||'')} • ID {c.external_campaign_id}</small></div><button className={c.provider_sync_enabled?'auto-on':'auto-off'} onClick={()=>toggleSync(c)}>{c.provider_sync_enabled?'Coleta ON':'Coleta OFF'}</button></article>)}</div>}
 <div className="sync-actions"><button onClick={()=>sync(false)} disabled={busy}><CloudDownload/> Sincronizar dados agora</button><button className="danger-soft" onClick={()=>sync(true)} disabled={busy}><RefreshCw/> Sincronizar + aplicar regras internas</button><span><ShieldCheck/> A segunda opção só altera campanhas internas com Automação ON; ainda não altera verba/status diretamente no Google ou Meta.</span></div>{msg&&<p className="growth-message">{msg}</p>}
 </section></>;
}
