import { FormEvent, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, BarChart3, CheckCircle2, Clock3, CreditCard, LogOut, Megaphone, Menu, RefreshCw, Search, ShieldCheck, Store, UsersRound, Wrench, X } from 'lucide-react';
import { supabase } from './lib/supabase';
import { Brand } from './Brand';
import type { AdminSubscription, AdminTenant } from './AdminCustomers';
import AdminCampaigns from './AdminCampaigns';
import AdminGrowthConnections from './AdminGrowthConnections';
import AdminGrowthAutomation from './AdminGrowthAutomation';
import AdminClientDirectory from './AdminClientDirectory';
import './admin.css';
import './payment-admin.css';
import './admin-workspace.css';

type Lead={id:string;name:string;whatsapp?:string;email?:string;business_name?:string;city?:string;source:string;campaign?:string;status:string;created_at:string};
type Tenant=AdminTenant&{activation_paid_at?:string|null;setup_requested_at?:string|null;setup_approved_at?:string|null;courtesy_type?:'tasting'|'barter'|null;courtesy_ends_at?:string|null};
type Sub=AdminSubscription;
type SetupReq={id:string;tenant_id:string;status:string;requested_at:string;assigned_admin?:string};
type AdminScreen='overview'|'clients'|'marketing'|'setup'|'leads'|'payments';
type SetupNotice={kind:'success'|'warning'|'error';text:string}|null;

const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
const screenMeta:Record<AdminScreen,{title:string;subtitle:string}>={
 overview:{title:'Resumo executivo',subtitle:'Indicadores essenciais e prioridades do dia.'},
 clients:{title:'Clientes',subtitle:'Carteira, edição, uso e relacionamento em visão 360º.'},
 marketing:{title:'Marketing & Growth',subtitle:'Campanhas, mídia, conexões, CAC, ROAS e automações.'},
 setup:{title:'Implantação',subtitle:'Preparação, homologação e liberação de ambientes.'},
 leads:{title:'Leads & CRM',subtitle:'Origem, estágio e contatos do funil comercial.'},
 payments:{title:'Pagamentos',subtitle:'Gateway, saúde da integração e cobrança da plataforma.'},
};

function setupErrorMessage(code?:string,detail?:string){
 const map:Record<string,string>={
  payment_required:'Pagamento da implantação ainda não confirmado. Confirme o pagamento ou libere uma cortesia válida no Cliente 360º.',
  courtesy_expired:'A cortesia deste cliente expirou. Renove a cortesia antes de liberar o ambiente.',
  forbidden:'Sua conta não possui permissão para alterar esta implantação.',
  unauthorized:'Sua sessão expirou. Entre novamente no Super Admin.',
  tenant_not_found:'Cliente não encontrado. Atualize a lista e tente novamente.',
  missing_tenant:'Cliente inválido para implantação.',
  invalid_action:'Ação de implantação inválida.',
  tenant_update_failed:'Não foi possível atualizar o ambiente do cliente.',
  internal_error:'O serviço de implantação encontrou um erro interno. Tente novamente em instantes.',
 };
 return map[code||'']||detail||'Não foi possível atualizar a implantação.';
}

export default function Admin(){
 const[session,setSession]=useState<any>(null);const[allowed,setAllowed]=useState<boolean|null>(null);const[mode,setMode]=useState<'login'|'signup'>('login');
 const[screen,setScreen]=useState<AdminScreen>('overview');const[mobileNav,setMobileNav]=useState(false);
 const[leads,setLeads]=useState<Lead[]>([]);const[tenants,setTenants]=useState<Tenant[]>([]);const[subs,setSubs]=useState<Sub[]>([]);const[requests,setRequests]=useState<SetupReq[]>([]);
 const[search,setSearch]=useState('');const[msg,setMsg]=useState('');const[paymentMsg,setPaymentMsg]=useState('');const[paymentBusy,setPaymentBusy]=useState(false);const[paymentStatus,setPaymentStatus]=useState<any>(null);const[busy,setBusy]=useState(false);const[actionBusy,setActionBusy]=useState<string|null>(null);const[setupNotice,setSetupNotice]=useState<SetupNotice>(null);
 useEffect(()=>{supabase?.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)loadAccess(data.session.user.id)})},[]);
 async function loadAccess(uid:string){if(!supabase)return;const{data}=await supabase.from('admin_users').select('role,active').eq('user_id',uid).maybeSingle();if(!data?.active){setAllowed(false);return}setAllowed(true);await Promise.all([refresh(),checkPayments()])}
 async function refresh(){if(!supabase)return;setBusy(true);const[l,t,s,r]=await Promise.all([supabase.from('leads').select('*').order('created_at',{ascending:false}).limit(500),supabase.from('tenants').select('id,name,phone,subscription_status,trial_ends_at,created_at,setup_status,activation_paid_at,setup_requested_at,setup_approved_at,courtesy_type,courtesy_started_at,courtesy_ends_at').order('created_at',{ascending:false}).limit(500),supabase.from('subscriptions').select('tenant_id,status,plan_code,provider_status'),supabase.from('setup_requests').select('id,tenant_id,status,requested_at,assigned_admin').order('requested_at',{ascending:false})]);setLeads((l.data||[]) as Lead[]);setTenants((t.data||[]) as Tenant[]);setSubs((s.data||[]) as Sub[]);setRequests((r.data||[]) as SetupReq[]);setBusy(false)}
 async function checkPayments(){try{const r=await fetch('https://pcrwtoddavpvkaxwtstc.supabase.co/functions/v1/mercadopago-health');setPaymentStatus(await r.json())}catch{setPaymentStatus(null)}}
 async function configurePayments(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setPaymentBusy(true);setPaymentMsg('');const f=new FormData(e.currentTarget);const{data,error}=await supabase.functions.invoke('configure-mercadopago',{body:{access_token:String(f.get('access_token')||''),webhook_secret:String(f.get('webhook_secret')||''),mode:String(f.get('mode')||'production')}});if(error){setPaymentMsg(`Falha de comunicação com o configurador: ${error.message}`)}else if(!data?.ok){const map:Record<string,string>={invalid_access_token:'Access Token rejeitado pelo Mercado Pago. Confira a aplicação e o ambiente.',missing_credentials:'Preencha Access Token e Webhook Secret.',vault_access_token_failed:'Não foi possível gravar o Access Token no cofre seguro.',vault_webhook_failed:'Não foi possível gravar a assinatura do webhook no cofre seguro.',vault_mode_failed:'Não foi possível gravar o ambiente no cofre seguro.',forbidden:'Esta conta não tem permissão para configurar o gateway.'};setPaymentMsg(map[data?.error]||`Falha: ${data?.error||'erro desconhecido'}${data?.detail?` — ${data.detail}`:''}`)}else{setPaymentMsg(`Mercado Pago conectado${data.nickname?` à conta ${data.nickname}`:''}.`);(e.currentTarget as HTMLFormElement).reset();await checkPayments()}setPaymentBusy(false)}
 async function manageSetup(tenantId:string,action:'start'|'approve'){
  if(!supabase)return;setSetupNotice(null);setActionBusy(tenantId+action);
  try{
   const{data,error}=await supabase.functions.invoke('manage-tenant-setup',{body:{tenant_id:tenantId,action}});
   if(error){setSetupNotice({kind:'error',text:setupErrorMessage(undefined,error.message)});return}
   if(!data?.ok){setSetupNotice({kind:data?.error==='payment_required'?'warning':'error',text:setupErrorMessage(data?.error,data?.detail)});return}
   setSetupNotice({kind:'success',text:action==='approve'?'Ambiente liberado com sucesso. O teste assistido de 3 dias foi iniciado.':'Preparação iniciada. O ambiente agora está em homologação.'});
   await refresh();
  }finally{setActionBusy(null)}
 }
 async function authenticate(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);setMsg('');const f=new FormData(e.currentTarget);const email=String(f.get('email'));const password=String(f.get('password'));if(mode==='signup'){const{data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:'https://meuespetinho.gritnews.com.br/admin'}});if(error)setMsg(error.message);else if(data.session){setSession(data.session);await loadAccess(data.session.user.id)}else setMsg('Conta criada. Confirme o e-mail e volte para entrar.');setBusy(false);return}const{data,error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message);else{setSession(data.session);await loadAccess(data.session.user.id)}setBusy(false)}
 async function logout(){await supabase?.auth.signOut();setSession(null);setAllowed(null)}
 const active=subs.filter(s=>s.status==='active').length,trials=tenants.filter(t=>t.subscription_status==='trialing').length,overdue=subs.filter(s=>s.status==='past_due').length;
 const funnel=useMemo(()=>['new','contacted','qualified','trial','proposal','won'].map(status=>({status,count:leads.filter(l=>l.status===status).length})),[leads]);
 const filtered=leads.filter(l=>`${l.name} ${l.business_name||''} ${l.whatsapp||''} ${l.email||''}`.toLowerCase().includes(search.toLowerCase()));
 const setupTenants=tenants.filter(t=>['awaiting_payment','pending_setup'].includes(t.setup_status||''));
 const nav=[{key:'overview' as const,label:'Resumo',icon:BarChart3},{key:'clients' as const,label:'Clientes',icon:UsersRound},{key:'marketing' as const,label:'Marketing & Growth',icon:Megaphone},{key:'setup' as const,label:'Implantação',icon:Wrench},{key:'leads' as const,label:'Leads & CRM',icon:Store},{key:'payments' as const,label:'Pagamentos',icon:CreditCard}];
 function go(next:AdminScreen){setScreen(next);setMobileNav(false);setSetupNotice(null);window.scrollTo({top:0,behavior:'smooth'})}
 if(!session)return <div className="admin-login"><div className="admin-login-card"><div className="admin-logo brand-admin"><Brand/></div><h1>{mode==='login'?'Acesso gerencial':'Criar acesso administrativo'}</h1><p>{mode==='login'?'Entre com sua conta administrativa.':'Use o e-mail autorizado e defina sua senha.'}</p><form onSubmit={authenticate}><input name="email" type="email" placeholder="E-mail" required/><input name="password" type="password" minLength={6} placeholder="Senha" required/><button disabled={busy}>{busy?'Aguarde...':mode==='login'?'Entrar':'Criar acesso'}</button>{msg&&<small>{msg}</small>}<small><a href="#" onClick={e=>{e.preventDefault();setMode(mode==='login'?'signup':'login');setMsg('')}}>{mode==='login'?'Primeiro acesso':'Voltar ao login'}</a></small></form></div></div>;
 if(allowed===false)return <div className="admin-login"><div className="admin-login-card"><ShieldCheck size={36}/><h1>Acesso protegido</h1><p>Conta autenticada, mas sem permissão de Super Admin.</p><small>{session.user.email}</small><button onClick={logout}>Sair</button></div></div>;
 if(allowed===null)return <div className="admin-loading">Validando acesso...</div>;
 return <div className="admin-shell admin-workspace"><aside className={mobileNav?'admin-sidebar open':'admin-sidebar'}><div className="admin-sidebar-top"><div className="admin-logo brand-admin"><Brand light/></div><button className="admin-nav-close" onClick={()=>setMobileNav(false)}><X/></button></div><span className="admin-context">SUPER ADMIN</span><nav>{nav.map(({key,label,icon:Icon})=><button key={key} className={screen===key?'admin-nav-item active':'admin-nav-item'} onClick={()=>go(key)}><Icon/><span>{label}</span>{key==='setup'&&setupTenants.length>0&&<b>{setupTenants.length}</b>}</button>)}</nav><div className="admin-sidebar-health"><span>Plataforma</span><strong>{paymentStatus?.configured?'Operacional':'Revisar integrações'}</strong><small>{active} assinante(s) ativo(s)</small></div><button className="admin-logout" onClick={logout}><LogOut/> Sair</button></aside><main><header className="admin-main-header"><button className="admin-menu-button" onClick={()=>setMobileNav(true)}><Menu/></button><div><small>PLATAFORMA</small><h1>{screenMeta[screen].title}</h1><p>{screenMeta[screen].subtitle}</p></div><button onClick={refresh}><RefreshCw className={busy?'spin':''}/> Atualizar</button></header>
 {screen==='overview'&&<div className="admin-screen-stack"><section className="admin-metrics"><article><span>Clientes</span><strong>{tenants.length}</strong><small>{active} assinantes ativos</small></article><article><span>MRR base</span><strong>{money(active*89)}</strong><small>{overdue} inadimplente(s)</small></article><article><span>Leads</span><strong>{leads.length}</strong><small>{trials} em trial</small></article><article><span>Implantações</span><strong>{setupTenants.length}</strong><small>aguardando ação</small></article></section><section className="admin-grid"><article className="admin-panel"><small>FUNIL</small><h2>Conversão comercial</h2><div className="funnel">{funnel.map((f,i)=><div key={f.status}><span>{['Novos','Contatados','Qualificados','Trial','Proposta','Ganhos'][i]}</span><b>{f.count}</b><i style={{width:`${leads.length?Math.max(7,(f.count/leads.length)*100):7}%`}}/></div>)}</div></article><article className="admin-panel"><small>PRIORIDADES</small><h2>O que precisa de atenção</h2><div className="mini-list"><button onClick={()=>go('setup')}><span>Ambientes a preparar</span><b>{setupTenants.length}</b></button><button onClick={()=>go('payments')}><span>Inadimplentes</span><b>{overdue}</b></button><button onClick={()=>go('clients')}><span>Clientes em trial</span><b>{trials}</b></button><button onClick={()=>go('marketing')}><span>Motor de Growth</span><b>→</b></button></div></article></section></div>}
 {screen==='clients'&&<AdminClientDirectory tenants={tenants} subs={subs} onRefresh={refresh}/>} 
 {screen==='marketing'&&<div className="admin-screen-stack"><div className="module-intro"><Megaphone/><div><small>AQUISIÇÃO</small><h2>Marketing & Growth</h2><p>Planejamento, mídia e automação ficam isolados do resumo executivo para uma leitura mais limpa da operação.</p></div></div><AdminCampaigns/><AdminGrowthConnections/><AdminGrowthAutomation/></div>}
 {screen==='setup'&&<section className="admin-panel setup-panel"><div className="panel-title"><div><small>IMPLANTAÇÃO</small><h2><Wrench/> Ambientes para preparar</h2><p>Pagamento confirmado ou cortesia válida são pré-requisitos para homologação e liberação.</p></div><span className={setupTenants.length?'gateway-status':'gateway-status ok'}>{setupTenants.length?`${setupTenants.length} pendente(s)`:'Fila em dia'}</span></div>{setupNotice&&<div className={`setup-notice ${setupNotice.kind}`}>{setupNotice.kind==='success'?<CheckCircle2/>:<AlertTriangle/>}<span>{setupNotice.text}</span><button onClick={()=>setSetupNotice(null)} aria-label="Fechar aviso"><X/></button></div>}{!setupTenants.length?<div className="setup-empty"><CheckCircle2/> Nenhuma implantação aguardando preparação.</div>:<div className="setup-list">{setupTenants.map(t=>{const req=requests.find(r=>r.tenant_id===t.id);const courtesyActive=Boolean(t.courtesy_type&&t.courtesy_ends_at&&new Date(t.courtesy_ends_at).getTime()>Date.now());const eligible=Boolean(t.activation_paid_at)||courtesyActive;const pendingPayment=t.setup_status==='awaiting_payment'&&!eligible;return <article key={t.id} className={pendingPayment?'setup-row blocked':'setup-row ready'}><div><div className="setup-row-title"><strong>{t.name}</strong><span className={`setup-state ${pendingPayment?'waiting':'ready'}`}>{pendingPayment?'Aguardando pagamento':'Pronto para implantação'}</span></div>{t.activation_paid_at?<span><CreditCard/> Pagamento confirmado em {new Date(t.activation_paid_at).toLocaleString('pt-BR')}</span>:courtesyActive?<span><CheckCircle2/> {t.courtesy_type==='barter'?'Permuta':'Degustação'} válida até {new Date(t.courtesy_ends_at!).toLocaleDateString('pt-BR')}</span>:<span><Clock3/> Pagamento ainda não confirmado</span>}<small>Status interno: {req?.status||t.setup_status||'pending'}</small></div><div className="setup-actions"><button className="secondary-admin" disabled={Boolean(actionBusy)||pendingPayment} onClick={()=>manageSetup(t.id,'start')}>{actionBusy===t.id+'start'?'Iniciando...':'Iniciar preparação'}</button><button disabled={Boolean(actionBusy)||pendingPayment} onClick={()=>manageSetup(t.id,'approve')}>{actionBusy===t.id+'approve'?'Liberando...':'Liberar ambiente'}</button>{pendingPayment&&<small className="setup-action-help">Confirme o pagamento ou use uma cortesia válida no Cliente 360º.</small>}</div></article>})}</div>}</section>}
 {screen==='leads'&&<section className="admin-panel leads-panel clean-panel"><div className="panel-title"><div><small>CRM</small><h2>Leads recentes</h2><p>Pesquise por empresa, contato, WhatsApp ou e-mail.</p></div><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar lead..."/></label></div><div className="lead-table"><div className="lead-head"><span>Lead</span><span>Origem</span><span>Status</span><span>Contato</span></div>{filtered.slice(0,250).map(l=><div className="lead-row" key={l.id}><span><b>{l.business_name||l.name}</b><small>{l.name}{l.city?` • ${l.city}`:''}</small></span><span><b>{l.source}</b><small>{l.campaign||'orgânico'}</small></span><span><em className={`status ${l.status}`}>{l.status}</em></span><span><b>{l.whatsapp||l.email||'-'}</b><small>{new Date(l.created_at).toLocaleDateString('pt-BR')}</small></span></div>)}</div></section>}
 {screen==='payments'&&<section className="admin-panel payment-panel clean-panel"><div className="panel-title"><div><small>GATEWAY</small><h2><CreditCard/> Mercado Pago</h2><p>Credenciais ficam protegidas no Supabase Vault e nunca são expostas no navegador.</p></div><span className={paymentStatus?.configured?'gateway-status ok':'gateway-status'}>{paymentStatus?.configured?'Conectado':'Configuração pendente'}</span></div><form className="payment-config" onSubmit={configurePayments}><label>Access Token<input type="password" name="access_token" autoComplete="off" placeholder="APP_USR-..." required/></label><label>Webhook Secret<input type="password" name="webhook_secret" autoComplete="off" placeholder="Assinatura secreta" required/></label><label>Ambiente<select name="mode" defaultValue="production"><option value="production">Produção</option><option value="test">Teste</option></select></label><button disabled={paymentBusy}>{paymentBusy?'Validando...':'Conectar e validar'}</button></form>{paymentMsg&&<p className="payment-message">{paymentMsg}</p>}<small className="webhook-url">Webhook: https://pcrwtoddavpvkaxwtstc.supabase.co/functions/v1/mercadopago-webhook</small><div className="gateway-help"><b>Saúde da cobrança:</b> pagamentos confirmados alimentam assinatura, receita e atribuição do Growth Engine.</div></section>}
 </main>{mobileNav&&<button className="admin-nav-overlay" aria-label="Fechar menu" onClick={()=>setMobileNav(false)}/>}</div>;
}
