import { FormEvent, useEffect, useMemo, useState } from 'react';
import { BarChart3, Flame, LogOut, RefreshCw, Search, ShieldCheck, Users, WalletCards } from 'lucide-react';
import { supabase } from './lib/supabase';
import './admin.css';
type Lead={id:string;name:string;whatsapp?:string;email?:string;business_name?:string;city?:string;source:string;campaign?:string;status:string;created_at:string};
type Tenant={id:string;name:string;subscription_status:string;trial_ends_at:string;created_at:string};
type Sub={tenant_id:string;status:string;plan_code:string;provider_status?:string};
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
export default function Admin(){const[session,setSession]=useState<any>(null);const[allowed,setAllowed]=useState<boolean|null>(null);const[mode,setMode]=useState<'login'|'signup'>('login');const[leads,setLeads]=useState<Lead[]>([]);const[tenants,setTenants]=useState<Tenant[]>([]);const[subs,setSubs]=useState<Sub[]>([]);const[search,setSearch]=useState('');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
useEffect(()=>{supabase?.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)loadAccess(data.session.user.id)})},[]);
async function loadAccess(userId?:string){if(!supabase)return;const uid=userId||(await supabase.auth.getUser()).data.user?.id;if(!uid){setAllowed(false);return}const{data,error}=await supabase.from('admin_users').select('role,active').eq('user_id',uid).maybeSingle();if(error||!data?.active){setAllowed(false);return}setAllowed(true);await refresh()}
async function refresh(){if(!supabase)return;setBusy(true);const[l,t,s]=await Promise.all([supabase.from('leads').select('*').order('created_at',{ascending:false}).limit(500),supabase.from('tenants').select('id,name,subscription_status,trial_ends_at,created_at').order('created_at',{ascending:false}).limit(500),supabase.from('subscriptions').select('tenant_id,status,plan_code,provider_status')]);setLeads((l.data||[]) as Lead[]);setTenants((t.data||[]) as Tenant[]);setSubs((s.data||[]) as Sub[]);setBusy(false)}
async function authenticate(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);setMsg('');const f=new FormData(e.currentTarget);const email=String(f.get('email'));const password=String(f.get('password'));if(mode==='signup'){const{data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:'https://app.meuespetinho.gritnews.com.br/admin'}});if(error){setMsg(error.message);setBusy(false);return}if(data.session){setSession(data.session);await loadAccess(data.session.user.id)}else setMsg('Conta criada. Confirme o e-mail e volte para entrar.');setBusy(false);return}const{data,error}=await supabase.auth.signInWithPassword({email,password});if(error){setMsg(error.message);setBusy(false);return}setSession(data.session);await loadAccess(data.session.user.id);setBusy(false)}
async function logout(){await supabase?.auth.signOut();setSession(null);setAllowed(null)}
const active=subs.filter(s=>s.status==='active').length;const trials=tenants.filter(t=>t.subscription_status==='trialing').length;const overdue=subs.filter(s=>s.status==='past_due').length;const won=leads.filter(l=>l.status==='won').length;const funnel=useMemo(()=>['new','contacted','qualified','trial','proposal','won'].map(status=>({status,count:leads.filter(l=>l.status===status).length})),[leads]);const filtered=leads.filter(l=>`${l.name} ${l.business_name||''} ${l.whatsapp||''} ${l.email||''}`.toLowerCase().includes(search.toLowerCase()));
if(!session)return <div className="admin-login"><div className="admin-login-card"><div className="admin-logo"><Flame/><div><b>Meu Espetinho</b><span>Super Admin</span></div></div><h1>{mode==='login'?'Acesso gerencial':'Criar acesso administrativo'}</h1><p>{mode==='login'?'Entre com sua conta administrativa.':'No primeiro acesso, use o e-mail autorizado e defina sua senha.'}</p><form onSubmit={authenticate}><input name="email" type="email" placeholder="E-mail" required/><input name="password" type="password" minLength={6} placeholder="Senha" required/><button disabled={busy}>{busy?'Aguarde...':mode==='login'?'Entrar':'Criar acesso'}</button>{msg&&<small>{msg}</small>}<small>{mode==='login'?'Primeiro acesso?':'Já criou o acesso?'} <a href="#" onClick={(e)=>{e.preventDefault();setMode(mode==='login'?'signup':'login');setMsg('')}}>{mode==='login'?'Criar senha de administrador':'Entrar'}</a></small></form></div></div>;
if(allowed===false)return <div className="admin-login"><div className="admin-login-card"><ShieldCheck size={36}/><h1>Acesso protegido</h1><p>Sua conta está autenticada, mas não está autorizada como Super Admin.</p><small>Usuário: {session.user.email}</small><button onClick={logout}>Sair</button></div></div>;
if(allowed===null)return <div className="admin-loading">Validando acesso...</div>;
return <div className="admin-shell"><aside><div className="admin-logo"><Flame/><div><b>Meu Espetinho</b><span>Super Admin</span></div></div><nav><a className="active"><BarChart3/> Visão geral</a><a><Users/> Leads e clientes</a><a><WalletCards/> Assinaturas</a></nav><button onClick={logout}><LogOut/> Sair</button></aside><main><header><div><small>PLATAFORMA</small><h1>Máquina de crescimento</h1><p>Acompanhe aquisição, trials, clientes e receita recorrente.</p></div><button onClick={refresh}><RefreshCw className={busy?'spin':''}/> Atualizar</button></header><section className="admin-metrics"><article><span>Leads</span><strong>{leads.length}</strong><small>capturados</small></article><article><span>Trials</span><strong>{trials}</strong><small>em teste</small></article><article><span>Assinantes ativos</span><strong>{active}</strong><small>{won} oportunidades ganhas</small></article><article><span>MRR</span><strong>{money(active*89)}</strong><small>{overdue} inadimplentes</small></article></section><section className="admin-grid"><article className="admin-panel"><div className="panel-title"><div><small>FUNIL</small><h2>Conversão comercial</h2></div></div><div className="funnel">{funnel.map((f,i)=><div key={f.status}><span>{['Novos','Contatados','Qualificados','Trial','Proposta','Ganhos'][i]}</span><b>{f.count}</b><i style={{width:`${leads.length?Math.max(7,(f.count/leads.length)*100):7}%`}}/></div>)}</div></article><article className="admin-panel"><small>CARTEIRA</small><h2>Clientes da plataforma</h2><div className="mini-list"><div><span>Total de empresas</span><b>{tenants.length}</b></div><div><span>Ativas</span><b>{active}</b></div><div><span>Trial</span><b>{trials}</b></div><div><span>Past due</span><b>{overdue}</b></div></div></article></section><section className="admin-panel leads-panel"><div className="panel-title"><div><small>CRM</small><h2>Leads recentes</h2></div><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar lead..."/></label></div><div className="lead-table"><div className="lead-head"><span>Lead</span><span>Origem</span><span>Status</span><span>Contato</span></div>{filtered.slice(0,100).map(l=><div className="lead-row" key={l.id}><span><b>{l.business_name||l.name}</b><small>{l.name}{l.city?` • ${l.city}`:''}</small></span><span><b>{l.source}</b><small>{l.campaign||'orgânico'}</small></span><span><em className={`status ${l.status}`}>{l.status}</em></span><span><b>{l.whatsapp||l.email||'-'}</b><small>{new Date(l.created_at).toLocaleDateString('pt-BR')}</small></span></div>)}</div></section></main></div>