import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {supabase} from './lib/supabase';
import './admin-client-period.css';

type PeriodKey='month'|'30d'|'60d'|'90d'|'6m'|'1y'|'custom';
type Row={tenant_id:string;tenant_name:string;orders_90d:number;revenue_90d:number;cmv_90d:number;gross_profit_90d:number;gross_margin_pct:number;products_count:number;products_with_cost:number};
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
const labels:Record<PeriodKey,string>={month:'mês atual','30d':'30 dias','60d':'60 dias','90d':'90 dias','6m':'6 meses','1y':'1 ano',custom:'período'};
function toLocalDate(d:Date){const y=d.getFullYear();const m=String(d.getMonth()+1).padStart(2,'0');const day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function bounds(key:PeriodKey,customStart:string,customEnd:string){const end=new Date();end.setSeconds(end.getSeconds()+1);let start=new Date(end);if(key==='month')start=new Date(end.getFullYear(),end.getMonth(),1);else if(key==='30d')start.setDate(start.getDate()-30);else if(key==='60d')start.setDate(start.getDate()-60);else if(key==='90d')start.setDate(start.getDate()-90);else if(key==='6m')start.setMonth(start.getMonth()-6);else if(key==='1y')start.setFullYear(start.getFullYear()-1);else{if(!customStart||!customEnd)return null;start=new Date(`${customStart}T00:00:00`);const customFinish=new Date(`${customEnd}T00:00:00`);customFinish.setDate(customFinish.getDate()+1);if(start>=customFinish)return null;return{start:start.toISOString(),end:customFinish.toISOString()}}return{start:start.toISOString(),end:end.toISOString()}}

export default function AdminClientCmvBridge(){
 const[rows,setRows]=useState<Row[]>([]);const[target,setTarget]=useState<Element|null>(null);const[filterTarget,setFilterTarget]=useState<Element|null>(null);const[name,setName]=useState('');const[period,setPeriod]=useState<PeriodKey>('90d');const[customStart,setCustomStart]=useState(()=>toLocalDate(new Date(Date.now()-30*86400000)));const[customEnd,setCustomEnd]=useState(()=>toLocalDate(new Date()));const[loading,setLoading]=useState(false);
 const range=useMemo(()=>bounds(period,customStart,customEnd),[period,customStart,customEnd]);const label=period==='custom'&&range?`${new Date(range.start).toLocaleDateString('pt-BR')} a ${new Date(new Date(range.end).getTime()-86400000).toLocaleDateString('pt-BR')}`:labels[period];
 useEffect(()=>{let alive=true;async function load(){if(!supabase||!range)return;setLoading(true);const{data,error}=await supabase.rpc('admin_customer_overview_period',{p_start:range.start,p_end:range.end});if(alive&&!error)setRows((data||[]) as Row[]);if(alive)setLoading(false)}load();return()=>{alive=false}},[range?.start,range?.end]);
 useEffect(()=>{const sync=()=>{const metric=document.querySelector('.customer-detail .detail-metrics');const title=document.querySelector('.customer-detail .detail-title h3')?.textContent?.trim()||'';const filter=document.querySelector('.customers-360 .panel-title');setTarget(metric);setFilterTarget(filter);setName(title)};sync();const observer=new MutationObserver(sync);observer.observe(document.body,{subtree:true,childList:true,characterData:true});return()=>observer.disconnect()},[]);
 const row=useMemo(()=>rows.find(r=>r.tenant_name===name)||null,[rows,name]);
 useEffect(()=>{const header=document.querySelector('.customer-list .customer-head span:nth-child(3)');if(header&&header.textContent!==`Uso ${label}`)header.textContent=`Uso ${label}`;document.querySelectorAll('.customer-list .customer-row').forEach(el=>{const nameEl=el.querySelector(':scope > span:first-child b');const tenantName=nameEl?.textContent?.trim();const data=rows.find(r=>r.tenant_name===tenantName);if(!data)return;const spans=el.querySelectorAll(':scope > span');const usage=spans[2];const b=usage?.querySelector('b');const small=usage?.querySelector('small');if(b&&b.textContent!==`${Number(data.orders_90d||0)} pedidos`)b.textContent=`${Number(data.orders_90d||0)} pedidos`;if(small&&!small.classList.contains('stale-note')){const txt=`${money(data.revenue_90d)} processados`;if(small.textContent!==txt)small.textContent=txt}});if(target&&row){const cards=target.querySelectorAll(':scope > div');const first=cards[0];const second=cards[1];const s1=first?.querySelector('span'),b1=first?.querySelector('b'),s2=second?.querySelector('span'),b2=second?.querySelector('b');if(s1)s1.textContent=`Pedidos ${label}`;if(b1)b1.textContent=String(Number(row.orders_90d||0));if(s2)s2.textContent=`Volume ${label}`;if(b2)b2.textContent=money(row.revenue_90d)}},[rows,row,target,label]);
 const coverage=row&&row.products_count>0?Math.round((Number(row.products_with_cost||0)/Number(row.products_count))*100):0;const reliable=coverage===100;
 const filter=filterTarget?createPortal(<div className="client-period-filter"><div className="cpf-head"><div><small>PERÍODO DA ANÁLISE</small><strong>{label}</strong></div>{loading&&<span>Atualizando...</span>}</div><div className="cpf-presets">{(['month','30d','60d','90d','6m','1y','custom'] as PeriodKey[]).map(k=><button key={k} className={period===k?'active':''} onClick={()=>setPeriod(k)}>{k==='month'?'Mês atual':k==='custom'?'Período específico':labels[k]}</button>)}</div>{period==='custom'&&<div className="cpf-custom"><label>De<input type="date" value={customStart} max={customEnd} onChange={e=>setCustomStart(e.target.value)}/></label><label>Até<input type="date" value={customEnd} min={customStart} onChange={e=>setCustomEnd(e.target.value)}/></label>{!range&&<em>Informe um período válido.</em>}</div>}<p>Faturamento, pedidos, CMV, lucro bruto e margem seguem este período. Saúde e status do assinante continuam operacionais.</p></div>,filterTarget):null;
 const metrics=target&&row?createPortal(<><div className="cmv-kpi"><span>CMV {label}</span><b>{money(row.cmv_90d)}</b><small>{reliable?'custos completos':'estimativa parcial'}</small></div><div className="cmv-kpi"><span>Lucro bruto {label}</span><b>{money(row.gross_profit_90d)}</b><small>faturamento − CMV</small></div><div className="cmv-kpi"><span>Margem bruta</span><b>{Number(row.gross_margin_pct||0).toFixed(1)}%</b><small>antes das despesas</small></div><div className={`cmv-kpi ${reliable?'cmv-ok':'cmv-warn'}`}><span>Cobertura de custo</span><b>{coverage}%</b><small>{row.products_with_cost}/{row.products_count} produtos com custo</small></div></>,target):null;
 return <>{filter}{metrics}</>;
}
