import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,CheckCircle2,Clock3,RefreshCw,RotateCcw,ShieldCheck,TrendingDown} from 'lucide-react';
import {supabase} from './lib/supabase';
import './admin-churn.css';

type Cancellation={id:string;tenant_id:string;reason_code?:string|null;within_cooling_off:boolean;status:string;refund_total:number;created_at:string};
type Tenant={id:string;name:string;subscription_status:string};
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0);
const labels:Record<string,string>={price:'Preço',low_usage:'Pouco uso',missing_feature:'Recurso faltante',technical_issue:'Problema técnico',not_adapted:'Não se adaptou',other:'Outro',prefer_not_to_say:'Não informado'};
export default function AdminChurn(){
 const[rows,setRows]=useState<Cancellation[]>([]);const[tenants,setTenants]=useState<Tenant[]>([]);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');
 async function load(){if(!supabase)return;setBusy(true);const[c,t]=await Promise.all([supabase.from('cancellation_requests').select('id,tenant_id,reason_code,within_cooling_off,status,refund_total,created_at').order('created_at',{ascending:false}).limit(500),supabase.from('tenants').select('id,name,subscription_status').limit(1000)]);setRows((c.data||[]) as Cancellation[]);setTenants((t.data||[]) as Tenant[]);setMsg(c.error?'Não foi possível carregar os dados financeiros.':'');setBusy(false)}
 useEffect(()=>{load()},[]);
 const cancelled=new Set(rows.filter(r=>['completed','refund_partial'].includes(r.status)).map(r=>r.tenant_id)).size;const rate=tenants.length?(cancelled/tenants.length)*100:0;const refunded=rows.reduce((s,r)=>s+Number(r.refund_total||0),0);const failures=rows.filter(r=>String(r.status).includes('failed')||r.status==='refund_partial').length;const cdc=rows.filter(r=>r.within_cooling_off).length;
 const reasons=useMemo(()=>{const m=new Map<string,number>();rows.forEach(r=>{const k=r.reason_code||'prefer_not_to_say';m.set(k,(m.get(k)||0)+1)});return [...m.entries()].sort((a,b)=>b[1]-a[1])},[rows]);
 const retention=useMemo(()=>{const x:string[]=[];if(reasons.some(r=>r[0]==='price'))x.push('Reforçar valor percebido e ROI no onboarding.');if(reasons.some(r=>r[0]==='missing_feature'))x.push('Cruzar recursos pedidos com o roadmap do produto.');if(reasons.some(r=>r[0]==='low_usage'))x.push('Criar onboarding de 3 dias com ações mínimas de uso.');if(reasons.some(r=>r[0]==='technical_issue'))x.push('Criar alerta proativo para falhas técnicas antes da saída.');return x.length?x:['Ainda não há volume suficiente para uma recomendação confiável.']},[reasons]);
 const tenantName=(id:string)=>tenants.find(t=>t.id===id)?.name||'Cliente';
 return <section className="admin-panel churn-panel clean-panel"><div className="panel-title"><div><small>FINANCEIRO</small><h2><TrendingDown/> Cancelamentos & Churn</h2><p>Taxa de saída, motivos, estornos, prazo CDC e oportunidades de retenção.</p></div><button className="secondary-admin" onClick={load} disabled={busy}><RefreshCw className={busy?'spin':''}/> Atualizar</button></div><div className="churn-metrics"><article><span>Taxa de cancelamento</span><strong>{rate.toFixed(1)}%</strong><small>{cancelled} cliente(s)</small></article><article><span>Valores estornados</span><strong>{money(refunded)}</strong><small>{cdc} caso(s) dentro de 7 dias</small></article><article><span>Falhas de reembolso</span><strong>{failures}</strong><small>exigem revisão</small></article><article><span>Solicitações</span><strong>{rows.length}</strong><small>histórico total</small></article></div><div className="churn-grid"><article><h3>Motivos</h3><div className="reason-list">{reasons.map(([k,n])=><div key={k}><span>{labels[k]||k}</span><b>{n}</b><i style={{width:`${Math.max(8,(n/Math.max(1,rows.length))*100)}%`}}/></div>)}</div></article><article><h3>Oportunidades de retenção</h3><div className="retention-list">{retention.map((r,i)=><p key={i}><CheckCircle2/> {r}</p>)}</div></article></div><div className="cancel-table"><div className="cancel-head"><span>Cliente</span><span>Pedido</span><span>CDC</span><span>Estorno</span><span>Status</span></div>{rows.map(r=>{const failed=String(r.status).includes('failed')||r.status==='refund_partial';return <div className="cancel-row" key={r.id}><span><b>{tenantName(r.tenant_id)}</b><small>{labels[r.reason_code||'prefer_not_to_say']||'Não informado'}</small></span><span><b>{new Date(r.created_at).toLocaleDateString('pt-BR')}</b></span><span>{r.within_cooling_off?<><ShieldCheck/> Dentro de 7 dias</>:<><Clock3/> Fora da janela</>}</span><span><b>{money(Number(r.refund_total||0))}</b></span><span><em className={failed?'churn-status danger':r.status==='completed'?'churn-status ok':'churn-status'}>{failed?<AlertTriangle/>:<RotateCcw/>}{r.status}</em></span></div>})}</div>{msg&&<p className="payment-message">{msg}</p>}</section>;
}
