import {FormEvent,useEffect,useMemo,useState} from 'react';
import {Bot,Edit3,ExternalLink,Plus,RefreshCw,Search,Target,Trash2,WandSparkles,Trophy,Lightbulb,Zap} from 'lucide-react';
import {supabase} from './lib/supabase';
import './competitive-radar.css';
type C={id:string;name:string;domain:string;segment?:string;priority:number;active:boolean;notes?:string;reference_urls?:string[];keywords?:string[]};
type T={id:string;term:string;cluster?:string;intent:string;priority:number;source:string;status:string};
type I={id:string;insight_type:string;title:string;description:string;priority:number;status:string;created_at:string};
type S={id:string;competitor_id:string;score_total:number;product_score:number;seo_score:number;offer_score:number;proof_score:number;niche_score:number;strengths:string[];weaknesses:string[];gaps:string[];calculated_at:string};
type A={id:string;competitor_id?:string;action_type:string;title:string;description:string;impact:number;effort:number;priority:number;status:string};
const arr=(v:string)=>v.split(/[\n,]/).map(x=>x.trim()).filter(Boolean);
const normalizeUrl=(v:string)=>/^https?:\/\//i.test(v.trim())?v.trim():`https://${v.trim()}`;
export default function AdminCompetitiveRadar(){const[cs,setCs]=useState<C[]>([]),[terms,setTerms]=useState<T[]>([]),[insights,setInsights]=useState<I[]>([]),[scores,setScores]=useState<S[]>([]),[actions,setActions]=useState<A[]>([]),[edit,setEdit]=useState<C|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
async function load(){if(!supabase)return;setBusy(true);const[c,t,i,s,a]=await Promise.all([supabase.from('seo_competitors').select('*').order('priority',{ascending:false}),supabase.from('seo_term_radar').select('*').eq('status','active').order('priority',{ascending:false}),supabase.from('seo_strategy_insights').select('*').eq('status','open').order('priority',{ascending:false}).limit(12),supabase.from('seo_competitor_scores').select('*').order('calculated_at',{ascending:false}),supabase.from('seo_strategy_actions').select('*').eq('status','open').order('priority',{ascending:false}).limit(12)]);setCs((c.data||[]) as C[]);setTerms((t.data||[]) as T[]);setInsights((i.data||[]) as I[]);setScores((s.data||[]) as S[]);setActions((a.data||[]) as A[]);setBusy(false)}useEffect(()=>{load()},[]);
const latestScore=(id:string)=>scores.find(s=>s.competitor_id===id);
async function enrich(id:string){if(!supabase)return false;setMsg('Analisando o site, oferta, funcionalidades e posição competitiva...');const{data,error}=await supabase.functions.invoke('competitor-enrich',{body:{competitor_id:id}});if(error||!data?.ok){setMsg(`Concorrente salvo, mas a análise automática não foi concluída${error?.message?`: ${error.message}`:'.'}`);return false}setMsg(`Análise V2 concluída: score ${data.score?.total||0}/100 • ${data.keywords?.length||0} sinais • ${data.references?.length||0} referências • ${data.actions?.length||0} ações estratégicas.`);return true}
async function saveCompetitor(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);const form=e.currentTarget;const f=new FormData(form);const p={name:String(f.get('name')).trim(),domain:normalizeUrl(String(f.get('domain'))),segment:String(f.get('segment')||'food service'),priority:Number(f.get('priority')||70),active:true,notes:String(f.get('notes')||''),reference_urls:arr(String(f.get('references')||'')),keywords:arr(String(f.get('keywords')||'')),updated_at:new Date().toISOString()};let id=edit?.id;let error:any=null;if(edit){const res=await supabase.from('seo_competitors').update(p).eq('id',edit.id).select('id').single();error=res.error;id=res.data?.id}else{const duplicate=cs.find(c=>{try{return new URL(normalizeUrl(c.domain)).hostname===new URL(p.domain).hostname}catch{return false}});if(duplicate){setMsg('Este domínio já está cadastrado. Abra o concorrente existente para atualizar.');setBusy(false);return}const res=await supabase.from('seo_competitors').insert(p).select('id').single();error=res.error;id=res.data?.id}if(error||!id){setMsg(`Não foi possível salvar${error?.message?`: ${error.message}`:'.'}`);setBusy(false);return}await enrich(id);setEdit(null);form.reset();await load();setBusy(false)}
async function enrichExisting(c:C){setBusy(true);await enrich(c.id);await load();setBusy(false)}
async function toggle(c:C){if(!supabase)return;await supabase.from('seo_competitors').update({active:!c.active,updated_at:new Date().toISOString()}).eq('id',c.id);load()}
async function addTerm(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget);const{error}=await supabase.from('seo_term_radar').upsert({term:String(f.get('term')).trim().toLowerCase(),cluster:String(f.get('cluster')||''),intent:String(f.get('intent')||'commercial'),priority:Number(f.get('priority')||80),source:'admin',status:'active',updated_at:new Date().toISOString()},{onConflict:'term'});setMsg(error?'Erro ao adicionar termo.':'Termo incluído no radar.');if(!error){e.currentTarget.reset();load()}}
async function run(){if(!supabase)return;setBusy(true);setMsg('Validando sitemap, termos e concorrentes...');const{data,error}=await supabase.functions.invoke('seo-growth-robot',{body:{source:'admin'}});if(error){setMsg(`Falha na execução: ${error.message}. A rodada não alterou dados não validados.`)}else if(!data?.ok){setMsg(`Robô interrompido com segurança: ${data?.error||'erro não identificado'}.`)}else{const warning=data.warnings?` • ${data.warnings} aviso(s) parcial(is)`:'';setMsg(`Radar atualizado: ${data.pages_checked||0} páginas • ${data.competitors_checked||0} concorrentes • ${data.actions_created||0} ação(ões) • ${data.competitor_changes||0} mudança(s)${warning}.`)}await load();setBusy(false)}
const active=useMemo(()=>cs.filter(x=>x.active).length,[cs]);const scored=useMemo(()=>cs.map(c=>({c,s:latestScore(c.id)})).filter(x=>x.s).sort((a,b)=>(b.s?.score_total||0)-(a.s?.score_total||0)),[cs,scores]);
return <section className="competitive-radar"><div className="cr-head"><div><small>INTELIGÊNCIA COMPETITIVA V2</small><h2><Target/> Radar de concorrentes e termos</h2><p>Informe o site do concorrente. O sistema analisa oferta, produto, SEO, prova social e especialização, gera score e transforma gaps em ações.</p></div><button onClick={run} disabled={busy}><RefreshCw className={busy?'spin':''}/> {busy?'Validando...':'Atualizar radar agora'}</button></div><div className="cr-stats"><article><strong>{active}</strong><span>concorrentes ativos</span></article><article><strong>{terms.length}</strong><span>termos monitorados</span></article><article><strong>{actions.length}</strong><span>ações estratégicas</span></article><article><Bot/><span>análise diária validada</span></article></div>
{scored.length>0&&<div className="cr-scoreboard"><div className="cr-score-title"><Trophy/><div><h3>Competitive Score</h3><p>Referencial interno para priorizar ameaças e oportunidades. Não representa participação de mercado.</p></div></div><div className="cr-score-grid">{scored.slice(0,6).map(({c,s})=><article key={c.id}><div className="cr-score-top"><strong>{c.name}</strong><b>{s!.score_total}</b></div><div className="score-bar"><i style={{width:`${s!.score_total}%`}}/></div><small>Produto {s!.product_score} • SEO {s!.seo_score} • Oferta {s!.offer_score} • Prova {s!.proof_score} • Nicho {s!.niche_score}</small>{s!.strengths?.length?<p><b>Forças:</b> {s!.strengths.slice(0,3).join(' • ')}</p>:null}{s!.gaps?.length?<p className="gap"><b>Gap para explorar:</b> {s!.gaps[0]}</p>:null}</article>)}</div></div>}
<div className="cr-grid"><div><h3>Concorrência</h3><div className="cr-list">{cs.map(c=>{const s=latestScore(c.id);return <article key={c.id} className={!c.active?'off':''}><div><strong>{c.name}{s?<span className="score-pill">{s.score_total}/100</span>:null}</strong><a href={normalizeUrl(c.domain)} target="_blank" rel="noreferrer">{c.domain.replace(/^https?:\/\//,'').split('/')[0]} <ExternalLink size={13}/></a><small>Prioridade {c.priority} • {c.segment||'food service'}</small>{c.keywords?.length?<p>{c.keywords.slice(0,7).join(' • ')}</p>:null}</div><div><button onClick={()=>enrichExisting(c)} title="Atualizar análise competitiva"><WandSparkles/></button><button onClick={()=>setEdit(c)} title="Editar"><Edit3/></button><button onClick={()=>toggle(c)} title={c.active?'Pausar':'Ativar'}><Trash2/></button></div></article>})}</div></div>
<form className="cr-form" onSubmit={saveCompetitor}><h3><Plus/> {edit?'Editar concorrente':'Adicionar concorrente'}</h3><p className="cr-helper">Preencha nome e site. Os demais campos podem ficar em branco: o robô analisa o domínio e tenta preenchê-los automaticamente.</p><label>Nome<input name="name" required defaultValue={edit?.name||''} key={`n${edit?.id||'new'}`}/></label><label>Site / URL principal<input name="domain" required defaultValue={edit?.domain||''} key={`d${edit?.id||'new'}`} placeholder="cardapioweb.com"/></label><label>Segmento<input name="segment" defaultValue={edit?.segment||'food service'}/></label><label>Prioridade<input name="priority" type="number" min="0" max="100" defaultValue={edit?.priority||70}/></label><label>Palavras / referências competitivas<textarea name="keywords" defaultValue={(edit?.keywords||[]).join('\n')} placeholder="Preenchimento automático após a análise"/></label><label>URLs de referência<textarea name="references" defaultValue={(edit?.reference_urls||[]).join('\n')} placeholder="Preenchimento automático após a análise"/></label><label>Notas<textarea name="notes" defaultValue={edit?.notes||''} placeholder="Título, descrição, ofertas e preços públicos encontrados aparecem aqui"/></label><div><button type="submit" disabled={busy}><WandSparkles/> {busy?'Analisando...':'Salvar e analisar site'}</button>{edit&&<button type="button" className="ghost" onClick={()=>setEdit(null)}>Cancelar</button>}</div></form></div>
<div className="cr-actions-board"><div className="cr-score-title"><Zap/><div><h3>Plano de conquista</h3><p>Ações geradas a partir dos gaps competitivos, priorizadas por impacto e esforço.</p></div></div><div className="strategy-actions">{!actions.length?<p>Nenhuma ação priorizada ainda. Atualize um concorrente para gerar recomendações.</p>:actions.map(a=><article key={a.id}><small>{a.action_type} • prioridade {a.priority}</small><strong>{a.title}</strong><p>{a.description}</p><span>Impacto {a.impact} • Esforço {a.effort}</span></article>)}</div></div>
<div className="cr-bottom"><div><h3><Search/> Robô de termos e palavras</h3><form className="term-form" onSubmit={addTerm}><input name="term" placeholder="Ex.: sistema para espetinho barato" required/><input name="cluster" placeholder="Cluster"/><select name="intent"><option value="transactional">Transacional</option><option value="commercial">Comercial</option><option value="informational">Informacional</option></select><input name="priority" type="number" min="0" max="100" defaultValue="80"/><button>Adicionar ao radar</button></form><div className="term-cloud">{terms.slice(0,24).map(t=><span key={t.id} title={`${t.intent} • prioridade ${t.priority}`}>{t.term}</span>)}</div></div><div><h3><Lightbulb/> Diferenciais e oportunidades</h3><div className="insights">{!insights.length?<p>O robô criará insights conforme acumular comparações.</p>:insights.map(i=><article key={i.id}><small>{i.insight_type} • P{i.priority}</small><strong>{i.title}</strong><p>{i.description}</p></article>)}</div></div></div>{msg&&<p className="cr-msg">{msg}</p>}</section>}
