import {FormEvent,useEffect,useState} from 'react';
import {CheckCircle2,Clock3,CreditCard,ShieldCheck} from 'lucide-react';
import App from './App';
import BillingAccount from './BillingAccount';
import {Brand} from './Brand';
import {supabase} from './lib/supabase';
import {trackMarketing} from './lib/analytics';
import './auth.css';

type Tenant={id:string;name:string;subscription_status:string;trial_ends_at:string;setup_status:'awaiting_payment'|'pending_setup'|'approved'|'suspended';courtesy_type?:'tasting'|'barter'|null;courtesy_ends_at?:string|null};
const ACTIVE_TENANT_KEY='meu-espetinho-active-tenant';
export default function AppGate(){
 const supportTenantId=new URLSearchParams(location.search).get('support_tenant');
 const[session,setSession]=useState<any>(undefined);const[tenant,setTenant]=useState<Tenant|null>(null);const[isAdmin,setIsAdmin]=useState(false);const[supportMode,setSupportMode]=useState(false);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);const[loadingTenant,setLoadingTenant]=useState(false);const[resetMode,setResetMode]=useState(new URLSearchParams(location.search).get('reset')==='1');
 useEffect(()=>{supabase?.auth.getSession().then(async({data})=>{setSession(data.session||null);if(data.session)await loadContext(data.session.user.id);else sessionStorage.removeItem(ACTIVE_TENANT_KEY)});const listener=supabase?.auth.onAuthStateChange(async(event,next)=>{if(event==='PASSWORD_RECOVERY'){setResetMode(true);setMsg('Link validado. Defina sua nova senha.')}setSession(next);if(next)await loadContext(next.user.id);else{sessionStorage.removeItem(ACTIVE_TENANT_KEY);setTenant(null);setIsAdmin(false);setSupportMode(false)}});return()=>listener?.data.subscription.unsubscribe()},[]);
 async function loadContext(uid:string){if(!supabase)return;setLoadingTenant(true);try{const[t,a]=await Promise.all([supabase.rpc('current_user_tenants'),supabase.from('admin_users').select('active').eq('user_id',uid).maybeSingle()]);if(t.error)throw t.error;const available=(t.data||[]) as Array<Tenant&{is_owner?:boolean}>;const adminActive=Boolean(a.data?.active);const requestedSupport=supportTenantId&&adminActive?available.find(x=>x.id===supportTenantId)||null:null;const selected=requestedSupport||(available.length?available[0]:null);if(selected)sessionStorage.setItem(ACTIVE_TENANT_KEY,selected.id);else sessionStorage.removeItem(ACTIVE_TENANT_KEY);setTenant(selected);setIsAdmin(adminActive);setSupportMode(Boolean(requestedSupport&&adminActive))}catch(error){console.error('Falha ao resolver contexto do usuário',error);sessionStorage.removeItem(ACTIVE_TENANT_KEY);setTenant(null);setIsAdmin(false);setSupportMode(false);setMsg('Não foi possível carregar seu ambiente agora. Tente novamente.')}finally{setLoadingTenant(false)}}
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);const f=new FormData(e.currentTarget);const{data,error}=await supabase.auth.signInWithPassword({email:String(f.get('email')),password:String(f.get('password'))});if(error)setMsg(error.message);else{setSession(data.session);await loadContext(data.session.user.id)}setBusy(false)}
 async function forgotPassword(){if(!supabase)return;const email=prompt('Informe o e-mail cadastrado para receber o link seguro de recuperação:','');if(!email)return;setBusy(true);const{error}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:'https://meuespetinho.gritnews.com.br/app?reset=1'});setMsg(error?'Não foi possível enviar agora. Aguarde e tente novamente.':'Se o e-mail estiver cadastrado, enviaremos um link de recuperação.');setBusy(false)}
 async function updatePassword(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget);const password=String(f.get('new_password')||'');const confirmation=String(f.get('confirm_password')||'');if(password.length<10){setMsg('Use uma senha com pelo menos 10 caracteres.');return}if(password!==confirmation){setMsg('As senhas não coincidem. Confira e tente novamente.');return}setBusy(true);const{error}=await supabase.auth.updateUser({password});if(error)setMsg('Não foi possível alterar a senha. Solicite um novo link.');else{setMsg('Senha alterada com sucesso.');setResetMode(false);history.replaceState({},'', '/app')}setBusy(false)}
 async function checkout(kind:'activation'|'subscription'){if(!supabase||!tenant)return;setBusy(true);setMsg('');trackMarketing({name:'begin_checkout',params:{kind,value:kind==='activation'?199:89,currency:'BRL'}});const fn=kind==='activation'?'create-activation-checkout':'create-subscription';const{data,error}=await supabase.functions.invoke(fn,{body:{tenant_id:tenant.id}});if(error||!data?.checkout_url){const code=data?.error||'';setMsg(code==='mercado_pago_not_configured'?'O pagamento online está em configuração. Fale com nosso atendimento para ativação assistida.':code==='invalid_access_token'?'Mercado Pago ainda não validado.':'Não foi possível abrir o pagamento agora.');setBusy(false);return}location.href=data.checkout_url}
 if(session===undefined||loadingTenant)return <div className="admin-loading">Carregando seu acesso...</div>;
 if(!session)return <div className="auth-page"><a className="auth-back" href="/">← Voltar</a><div className="auth-grid"><section><div className="admin-logo brand-admin"><Brand/></div><h1>Entre no seu ambiente.</h1><p>Mesas, clientes, fiado, equipe e resultados em um só lugar.</p></section><form onSubmit={login}><h2>Entrar</h2><label>E-mail<input name="email" type="email" required/></label><label>Senha<input name="password" type="password" required/></label><button disabled={busy}>{busy?'Entrando...':'Entrar'}</button><button type="button" className="setup-secondary" disabled={busy} onClick={forgotPassword}>Esqueci minha senha</button>{msg&&<p className="auth-message">{msg}</p>}<small>Primeiro acesso? <a href="/cadastro">Criar conta</a></small></form></div></div>;
 if(resetMode&&session)return <div className="setup-gate"><form className="setup-card" onSubmit={updatePassword}><ShieldCheck size={42}/><h1>Crie uma nova senha</h1><p>Use pelo menos 10 caracteres.</p><input name="new_password" type="password" minLength={10} autoComplete="new-password" required placeholder="Nova senha"/><input name="confirm_password" type="password" minLength={10} autoComplete="new-password" required placeholder="Confirme a nova senha"/><button className="setup-primary" disabled={busy}>{busy?'Salvando...':'Salvar nova senha'}</button>{msg&&<p className="auth-message">{msg}</p>}</form></div>;
 if(!tenant&&isAdmin)return <div className="setup-gate"><div className="setup-card"><ShieldCheck size={42}/><span className="auth-kicker">ACESSO ADMINISTRATIVO</span><h1>Seu acesso é de Super Admin.</h1><p>Esta conta administra a plataforma e não possui um estabelecimento operacional vinculado.</p><a className="setup-primary" href="/admin">Abrir Super Admin</a><a className="setup-secondary" href="/">Voltar ao site</a></div></div>;
 if(!tenant)return <div className="setup-gate"><div className="setup-card"><Clock3 size={42}/><h1>Cadastro ainda não vinculado a uma operação.</h1><p>Entre em contato com o suporte para concluirmos a configuração do seu estabelecimento.</p><a className="setup-primary" href="/contato?assunto=suporte">Falar com suporte</a></div></div>;
 const courtesyActive=Boolean(tenant.courtesy_type&&tenant.courtesy_ends_at&&new Date(tenant.courtesy_ends_at).getTime()>Date.now());
 if(!supportMode&&!courtesyActive&&tenant.setup_status==='awaiting_payment')return <div className="setup-gate"><div className="setup-card"><CreditCard size={42}/><span className="auth-kicker">ETAPA 1 DE 3</span><h1>Ative a implantação do seu ambiente.</h1><p><strong>{tenant.name}</strong> já está cadastrado. O setup inicial de <strong>R$ 199</strong> inicia a preparação assistida do seu sistema.</p><div className="setup-steps"><span className="active">1. Pagamento</span><span>2. Preparação</span><span>3. Liberação</span></div><button className="setup-primary" disabled={busy} onClick={()=>checkout('activation')}>{busy?'Abrindo pagamento...':'Pagar setup de R$ 199'}</button>{msg&&<p className="auth-message">{msg}</p>}<small>Após a confirmação, nossa equipe recebe automaticamente a solicitação de preparação.</small></div></div>;
 if(!supportMode&&!courtesyActive&&tenant.setup_status==='pending_setup')return <div className="setup-gate"><div className="setup-card"><Clock3 size={42}/><span className="auth-kicker">ETAPA 2 DE 3</span><h1>Pagamento confirmado. Ambiente em preparação.</h1><p>O Super Admin já recebeu sua solicitação. Agora configuramos a base da operação antes de liberar a personalização.</p><div className="setup-steps"><span className="done">✓ Pagamento</span><span className="active">2. Preparação</span><span>3. Liberação</span></div><small>Você poderá acessar produtos, usuários, identidade e configurações assim que o ambiente for liberado.</small></div></div>;
 if(!supportMode&&tenant.setup_status==='suspended')return <div className="setup-gate"><div className="setup-card"><ShieldCheck size={42}/><h1>Acesso temporariamente suspenso.</h1><p>Fale com o suporte do Meu Espetinho para revisar a situação do ambiente.</p><a className="setup-primary" href="/contato?assunto=suporte">Falar com suporte</a></div></div>;
 const accessEnd=courtesyActive?tenant.courtesy_ends_at:tenant.trial_ends_at;const days=Math.max(0,Math.ceil((new Date(accessEnd||'').getTime()-Date.now())/86400000));const trialActive=new Date(tenant.trial_ends_at).getTime()>Date.now();
 if(!supportMode&&tenant.subscription_status!=='active'&&!courtesyActive&&!trialActive)return <div className="setup-gate"><div className="setup-card"><Clock3 size={42}/><span className="auth-kicker">PERÍODO ENCERRADO</span><h1>Seu acesso assistido terminou.</h1><p>Assine o Meu Espetinho para continuar usando seu ambiente e manter seus dados disponíveis.</p><button className="setup-primary" disabled={busy} onClick={()=>checkout('subscription')}>{busy?'Abrindo pagamento...':'Assinar por R$ 89/mês'}</button>{msg&&<p className="auth-message">{msg}</p>}<a className="setup-secondary" href="/contato?assunto=suporte">Falar com suporte</a></div></div>;
 const accessLabel=courtesyActive?(tenant.courtesy_type==='barter'?'Permuta':'Degustação'):'Teste assistido';
 return <><App tenantId={tenant.id} userId={session.user.id}/>{!supportMode&&<BillingAccount tenantId={tenant.id}/>} {supportMode?<div className="billing-banner"><strong><ShieldCheck size={16}/> Modo suporte • {tenant.name}</strong><small>Acesso administrativo auditado. Bloqueios comerciais de pagamento, trial e suspensão não impedem a análise do Super Admin.</small><div className="billing-actions"><a href="/admin">Voltar ao Super Admin</a></div></div>:tenant.subscription_status!=='active'&&<div className="billing-banner"><strong><CheckCircle2 size={16}/> {accessLabel} liberada • {days} dia(s) restante(s)</strong><small>Mensalidade R$ 89 com até 3 usuários • usuários adicionais + R$ 39/mês cada.</small><div className="billing-actions"><button disabled={busy} onClick={()=>checkout('subscription')}>Assinar R$ 89/mês</button></div>{msg&&<small>{msg}</small>}</div>}</>;
}
