import { FormEvent, useEffect, useState } from 'react';
import { CheckCircle2, Clock3, CreditCard, ShieldCheck } from 'lucide-react';
import App from './App';
import { supabase } from './lib/supabase';
import { trackMarketing } from './lib/analytics';
import './auth.css';

type Tenant={id:string;name:string;subscription_status:string;trial_ends_at:string;setup_status:'awaiting_payment'|'pending_setup'|'approved'|'suspended';courtesy_type?:'tasting'|'barter'|null;courtesy_ends_at?:string|null};
const ACTIVE_TENANT_KEY='meu-espetinho-active-tenant';
export default function AppGate(){
 const[session,setSession]=useState<any>(undefined);const[tenant,setTenant]=useState<Tenant|null>(null);const[isAdmin,setIsAdmin]=useState(false);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);const[loadingTenant,setLoadingTenant]=useState(false);
 useEffect(()=>{supabase?.auth.getSession().then(async({data})=>{setSession(data.session||null);if(data.session)await loadContext(data.session.user.id);else sessionStorage.removeItem(ACTIVE_TENANT_KEY)});const listener=supabase?.auth.onAuthStateChange(async(_event,next)=>{setSession(next);if(next)await loadContext(next.user.id);else{sessionStorage.removeItem(ACTIVE_TENANT_KEY);setTenant(null);setIsAdmin(false)}});return()=>listener?.data.subscription.unsubscribe()},[]);
 async function loadContext(uid:string){if(!supabase)return;setLoadingTenant(true);try{const[t,a]=await Promise.all([supabase.rpc('current_user_tenants'),supabase.from('admin_users').select('active').eq('user_id',uid).maybeSingle()]);if(t.error)throw t.error;const available=(t.data||[]) as Array<Tenant&{is_owner?:boolean}>;const selected=available.length?available[0]:null;if(selected)sessionStorage.setItem(ACTIVE_TENANT_KEY,selected.id);else sessionStorage.removeItem(ACTIVE_TENANT_KEY);setTenant(selected);setIsAdmin(Boolean(a.data?.active))}catch(error){console.error('Falha ao resolver contexto do usuÃ¡rio',error);sessionStorage.removeItem(ACTIVE_TENANT_KEY);setTenant(null);setIsAdmin(false);setMsg('NÃ£o foi possÃ­vel carregar seu ambiente agora. Tente novamente.')}finally{setLoadingTenant(false)}}
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);const f=new FormData(e.currentTarget);const{data,error}=await supabase.auth.signInWithPassword({email:String(f.get('email')),password:String(f.get('password'))});if(error)setMsg(error.message);else{setSession(data.session);await loadContext(data.session.user.id)}setBusy(false)}
 async function checkout(kind:'activation'|'subscription'){if(!supabase||!tenant)return;setBusy(true);setMsg('');trackMarketing({name:'begin_checkout',params:{kind,value:kind==='activation'?199:89,currency:'BRL'}});const fn=kind==='activation'?'create-activation-checkout':'create-subscription';const{data,error}=await supabase.functions.invoke(fn,{body:{tenant_id:tenant.id}});if(error||!data?.checkout_url){const code=data?.error||'';setMsg(code==='mercado_pago_not_configured'?'O pagamento online estÃ¡ em configuraÃ§Ã£o. Fale com nosso atendimento para ativaÃ§Ã£o assistida.':code==='invalid_access_token'?'Mercado Pago ainda nÃ£o validado.':'NÃ£o foi possÃ­vel abrir o pagamento agora.');setBusy(false);return}location.href=data.checkout_url}
 if(session===undefined||loadingTenant)return <div className="admin-loading">Carregando seu acesso...</div>;
 if(!session)return <div className="auth-page"><a className="auth-back" href="/">â† Voltar</a><div className="auth-grid"><section><div className="admin-logo"><span className="brand-app-icon">â™¨</span><div><b>Meu Espetinho</b><small>SEU NEGÃ“CIO NO CONTROLE</small></div></div><h1>Entre no seu ambiente.</h1><p>Mesas, clientes, fiado, equipe e resultados em um sÃ³ lugar.</p></section><form onSubmit={login}><h2>Entrar</h2><label>E-mail<input name="email" type="email" required/></label><label>Senha<input name="password" type="password" required/></label><button disabled={busy}>{busy?'Entrando...':'Entrar'}</button>{msg&&<p className="auth-message">{msg}</p>}<small>Primeiro acesso? <a href="/cadastro">Criar conta</a></small></form></div></div>;
 if(!tenant&&isAdmin)return <div className="setup-gate"><div className="setup-card"><ShieldCheck size={42}/><span className="auth-kicker">ACESSO ADMINISTRATIVO</span><h1>Seu acesso Ã© de Super Admin.</h1><p>Esta conta administra a plataforma e nÃ£o possui um estabelecimento operacional vinculado.</p><a className="setup-primary" href="/admin">Abrir Super Admin</a><a className="setup-secondary" href="/">Voltar ao site</a></div></div>;
 if(!tenant)return <div className="setup-gate"><div className="setup-card"><Clock3 size={42}/><h1>Cadastro ainda nÃ£o vinculado a uma operaÃ§Ã£o.</h1><p>Entre em contato com o suporte para concluirmos a configuraÃ§Ã£o do seu estabelecimento.</p><a className="setup-primary" href="/contato?assunto=suporte">Falar com suporte</a></div></div>;
 const courtesyActive=Boolean(tenant.courtesy_type&&tenant.courtesy_ends_at&&new Date(tenant.courtesy_ends_at).getTime()>Date.now());
 if(!courtesyActive&&tenant.setup_status==='awaiting_payment')return <div className="setup-gate"><div className="setup-card"><CreditCard size={42}/><span className="auth-kicker">ETAPA 1 DE 3</span><h1>Ative a implantaÃ§Ã£o do seu ambiente.</h1><p><strong>{tenant.name}</strong> jÃ¡ estÃ¡ cadastrado. O setup inicial de <strong>R$ 199</strong> inicia a preparaÃ§Ã£o assistida do seu sistema.</p><div className="setup-steps"><span className="active">1. Pagamento</span><span>2. PreparaÃ§Ã£o</span><span>3. LiberaÃ§Ã£o</span></div><button className="setup-primary" disabled={busy} onClick={()=>checkout('activation')}>{busy?'Abrindo pagamento...':'Pagar setup de R$ 199'}</button>{msg&&<p className="auth-message">{msg}</p>}<small>ApÃ³s a confirmaÃ§Ã£o, nossa equipe recebe automaticamente a solicitaÃ§Ã£o de preparaÃ§Ã£o.</small></div></div>;
 if(!courtesyActive&&tenant.setup_status==='pending_setup')return <div className="setup-gate"><div className="setup-card"><Clock3 size={42}/><span className="auth-kicker">ETAPA 2 DE 3</span><h1>Pagamento confirmado. Ambiente em preparaÃ§Ã£o.</h1><p>O Super Admin jÃ¡ recebeu sua solicitaÃ§Ã£o. Agora configuramos a base da operaÃ§Ã£o antes de liberar a personalizaÃ§Ã£o.</p><div className="setup-steps"><span className="done">âœ“ Pagamento</span><span className="active">2. PreparaÃ§Ã£o</span><span>3. LiberaÃ§Ã£o</span></div><small>VocÃª poderÃ¡ acessar produtos, usuÃ¡rios, identidade e configuraÃ§Ãµes assim que o ambiente for liberado.</small></div></div>;
 if(tenant.setup_status==='suspended')return <div className="setup-gate"><div className="setup-card"><ShieldCheck size={42}/><h1>Acesso temporariamente suspenso.</h1><p>Fale com o suporte do Meu Espetinho para revisar a situaÃ§Ã£o do ambiente.</p><a className="setup-primary" href="/contato?assunto=suporte">Falar com suporte</a></div></div>;
 const accessEnd=courtesyActive?tenant.courtesy_ends_at:tenant.trial_ends_at;const days=Math.max(0,Math.ceil((new Date(accessEnd||'').getTime()-Date.now())/86400000));const trialActive=new Date(tenant.trial_ends_at).getTime()>Date.now();
 if(tenant.subscription_status!=='active'&&!courtesyActive&&!trialActive)return <div className="setup-gate"><div className="setup-card"><Clock3 size={42}/><span className="auth-kicker">PERÃODO ENCERRADO</span><h1>Seu acesso assistido terminou.</h1><p>Assine o Meu Espetinho para continuar usando seu ambiente e manter seus dados disponÃ­veis.</p><button className="setup-primary" disabled={busy} onClick={()=>checkout('subscription')}>{busy?'Abrindo pagamento...':'Assinar por R$ 89/mÃªs'}</button>{msg&&<p className="auth-message">{msg}</p>}<a className="setup-secondary" href="/contato?assunto=suporte">Falar com suporte</a></div></div>;
 const accessLabel=courtesyActive?(tenant.courtesy_type==='barter'?'Permuta':'DegustaÃ§Ã£o'):'Teste assistido';
 return <><App tenantId={tenant.id} userId={session.user.id}/>{tenant.subscription_status!=='active'&&<div className="billing-banner"><strong><CheckCircle2 size={16}/> {accessLabel} liberada â€¢ {days} dia(s) restante(s)</strong><small>Mensalidade R$ 89 com atÃ© 3 usuÃ¡rios â€¢ usuÃ¡rios adicionais + R$ 39/mÃªs cada.</small><div className="billing-actions"><button disabled={busy} onClick={()=>checkout('subscription')}>Assinar R$ 89/mÃªs</button></div>{msg&&<small>{msg}</small>}</div>}</>;
}

