import {useEffect,useState} from 'react';
import {CreditCard,ShieldCheck,XCircle} from 'lucide-react';
import {supabase} from './lib/supabase';
import './billing-account.css';

type Eligibility={contract_start?:string;cooling_off_deadline?:string;within_cooling_off?:boolean;subscription_status?:string;provider_subscription_id?:string|null};
export default function BillingAccount({tenantId}:{tenantId:string}){
 const[elig,setElig]=useState<Eligibility|null>(null);const[open,setOpen]=useState(false);const[reason,setReason]=useState('prefer_not_to_say');const[detail,setDetail]=useState('');const[confirm,setConfirm]=useState(false);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');
 useEffect(()=>{let active=true;(async()=>{try{const{data,error}=await supabase?.rpc('cancellation_eligibility',{p_tenant_id:tenantId})??{data:null,error:null};if(active&&!error&&data)setElig(data as Eligibility)}catch{}})();return()=>{active=false}},[tenantId]);
 if(!elig)return null;
 const deadline=elig.cooling_off_deadline?new Date(elig.cooling_off_deadline):null;
 async function cancel(){if(!supabase||!confirm||busy)return;setBusy(true);setMsg('Processando sua solicitação...');const{data,error}=await supabase.functions.invoke('cancel-subscription',{body:{tenant_id:tenantId,reason_code:reason,reason_detail:detail.trim()||null}});if(error){setMsg('Não foi possível concluir agora. Sua solicitação não foi perdida: fale com o suporte para atendimento imediato.');setBusy(false);return}const refund=Number(data?.refund_total||0);setMsg(data?.within_cooling_off?`Cancelamento concluído. Estorno solicitado: ${refund.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}.`:'Cancelamento concluído. A recorrência foi encerrada.');setBusy(false);setConfirm(false)}
 return <div className="billing-account"><button className="billing-account-link" onClick={()=>setOpen(!open)}><CreditCard size={15}/> Conta e cobrança</button>{open&&<div className="billing-account-card"><div className="billing-account-head"><div><small>CONTA E COBRANÇA</small><h3>Assinatura do Meu Espetinho</h3></div><button onClick={()=>setOpen(false)} aria-label="Fechar">×</button></div><div className="billing-status"><ShieldCheck size={18}/><div><strong>{elig.within_cooling_off?'Prazo de arrependimento ativo':'Assinatura e recorrência'}</strong><span>{elig.within_cooling_off&&deadline?`Você pode desistir até ${deadline.toLocaleString('pt-BR')}. O cancelamento nessa janela prevê devolução dos valores pagos nesta contratação.`:'Você pode cancelar a renovação da assinatura. Casos de reembolso fora do prazo legal podem ser analisados pelo suporte.'}</span></div></div><details className="billing-cancel"><summary>Cancelar assinatura</summary><div className="billing-cancel-body"><p>O motivo abaixo é <strong>opcional</strong> e serve apenas para melhorarmos o produto. Você pode escolher “Prefiro não informar”.</p><label>Motivo<select value={reason} onChange={e=>setReason(e.target.value)}><option value="prefer_not_to_say">Prefiro não informar</option><option value="price">Preço</option><option value="low_usage">Pouco uso</option><option value="missing_feature">Faltou algum recurso</option><option value="technical_issue">Dificuldade técnica</option><option value="not_adapted">Não se adaptou à operação</option><option value="other">Outro</option></select></label><label>Comentário opcional<textarea rows={3} value={detail} onChange={e=>setDetail(e.target.value)} placeholder="Se quiser, conte o que poderíamos melhorar."/></label><label className="billing-confirm"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/><span>Confirmo que quero cancelar a assinatura e encerrar a recorrência. Entendo que, quando aplicável, o estorno será solicitado ao Mercado Pago.</span></label><button className="billing-danger" disabled={!confirm||busy} onClick={cancel}><XCircle size={17}/>{busy?'Processando...':'Confirmar cancelamento'}</button>{msg&&<p className="billing-message">{msg}</p>}<small>Você também pode solicitar atendimento em <a href="/contato?assunto=cancelamento">Falar com suporte</a>.</small></div></details></div>}</div>
}