import { useEffect, useState } from 'react';
import { BarChart3, ShieldCheck, Store } from 'lucide-react';
import { supabase } from './lib/supabase';
import { Brand } from './Brand';
import AdminUnifiedLeads from './AdminUnifiedLeads';
import './admin.css';
import './admin-workspace.css';

type Lead={id:string;name?:string;business_name?:string;whatsapp?:string;email?:string;status?:string;source?:string;source_platform?:string;source_type?:string;campaign?:string;product?:string;created_at?:string;owner_email?:string;priority?:string;next_action?:string;next_action_at?:string;potential_value?:number|null;notes?:string;score?:number};
const COMMERCIAL_EMAIL='contato@gritnews.com.br';
const COMMERCIAL_WHATSAPP='5585921716546';
const products=[{key:'meu-espetinho',name:'Meu Espetinho'},{key:'sr-padeiro',name:'Sr. Padeiro'},{key:'sac-4',name:'SAC 4.0'},{key:'oportunidades-pro',name:'OportunidadesPro'}];
const digits=(v?:string)=>String(v||'').replace(/\D/g,'');
function inferProduct(l:Lead){const p=(l.product||'').toLowerCase();if(p.includes('padeiro'))return 'sr-padeiro';if(p.includes('sac'))return 'sac-4';if(p.includes('oportun'))return 'oportunidades-pro';return 'meu-espetinho'}
function productName(l:Lead){return products.find(p=>p.key===inferProduct(l))?.name||'GRIT'}
function whatsappUrl(l:Lead){const phone=digits(l.whatsapp)||COMMERCIAL_WHATSAPP;const first=(l.name||'').trim().split(' ')[0]||'Olá';const app=productName(l);return `https://wa.me/${phone}?text=${encodeURIComponent(`${first}, tudo bem? Aqui é da GRIT Soluções. Recebemos seu interesse no ${app}. Quero entender sua operação e te mostrar de forma objetiva como podemos ajudar. Podemos falar por aqui?`)}`}
function emailUrl(l:Lead){const to=l.email||COMMERCIAL_EMAIL;const app=productName(l);const subject=`GRIT | ${app} — próximo passo`;const body=`${l.name||'Olá'},\n\nRecebemos seu interesse no ${app}. Quero entender rapidamente sua rotina e indicar o próximo passo mais adequado.\n\nSe preferir, seguimos pelo WhatsApp +55 85 92171-6546.\n\nEquipe Comercial GRIT\n${COMMERCIAL_EMAIL}`;return `mailto:${to}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}
export default function GritLeadsCrm(){const[session,setSession]=useState<any>(null);const[allowed,setAllowed]=useState<boolean|null>(null);const[leads,setLeads]=useState<Lead[]>([]);const[product,setProduct]=useState('all');const[query,setQuery]=useState('');
 async function refresh(){if(!supabase)return;let q=supabase.from('leads').select('*').order('created_at',{ascending:false}).limit(1500);const{data}=await q;setLeads((data||[]) as Lead[])}
 useEffect(()=>{if(!supabase){setAllowed(false);return}supabase.auth.getSession().then(async({data})=>{setSession(data.session);if(!data.session){setAllowed(false);return}const{data:a}=await supabase!.from('admin_users').select('role,active').eq('user_id',data.session.user.id).maybeSingle();const ok=Boolean(a?.active&&['superadmin','owner','admin'].includes(String(a.role||'').toLowerCase()));setAllowed(ok);if(ok)await refresh()})},[]);
 const scoped=leads.filter(l=>product==='all'||inferProduct(l)===product).filter(l=>`${l.name||''} ${l.business_name||''} ${l.email||''} ${l.whatsapp||''}`.toLowerCase().includes(query.toLowerCase()));
 if(!session)return <div className="admin-login"><div className="admin-login-card"><ShieldCheck/><h1>CRM GRIT</h1><p>Entre primeiro pelo gerenciador administrativo.</p><a href="/admin">Abrir gerenciador</a></div></div>;
 if(allowed===false)return <div className="admin-login"><div className="admin-login-card"><ShieldCheck/><h1>Acesso protegido</h1><a href="/admin">Voltar</a></div></div>;if(allowed===null)return <div className="admin-loading">Validando acesso...</div>;
 return <div className="admin-shell admin-workspace"><aside className="admin-sidebar open"><div className="admin-sidebar-top"><div className="admin-logo brand-admin"><Brand light/></div></div><span className="admin-context">GRIT CRM</span><nav><a className="admin-nav-item" href="/admin/apps"><BarChart3/><span>Central GRIT</span></a><a className="admin-nav-item active" href="/admin/apps/leads"><Store/><span>Leads & Oportunidades</span></a></nav><div className="admin-sidebar-health"><span>Contato comercial</span><strong>{COMMERCIAL_EMAIL}</strong><small>+55 85 92171-6546</small></div></aside><main><header className="admin-main-header"><div><small>COMERCIAL GRIT</small><h1>Leads & Oportunidades</h1><p>Roteie cada lead para o app correto, defina responsável, próxima ação e amadureça a oportunidade até a venda.</p></div></header><div className="admin-screen-stack"><section className="admin-panel"><div className="panel-title"><div><small>ROTEAMENTO</small><h2>Pipeline multi-app</h2><p>Todo lead entra na central e deve sair com produto, responsável e próxima ação definidos.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><select value={product} onChange={e=>setProduct(e.target.value)}><option value="all">Todos os apps</option>{products.map(p=><option value={p.key} key={p.key}>{p.name}</option>)}</select><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nome, empresa, e-mail ou WhatsApp"/></div></div></section><AdminUnifiedLeads leads={scoped} onRefresh={refresh} productName={productName} whatsappUrl={whatsappUrl} emailUrl={emailUrl}/></div></main></div>}
