import { ArrowRight, BarChart3, Check, CreditCard, Headphones, Menu, ReceiptText, ShieldCheck, ShoppingCart, Store, TrendingUp, UserCog, Users, WalletCards, X } from 'lucide-react';
import { useState } from 'react';
import { Brand } from './Brand';
import LeadForm from './LeadForm';
import './landing.css';

const benefits=[
 {icon:ShoppingCart,title:'Operação firme e rápida',text:'PDV simples para vender em poucos toques, com organização do início ao fechamento.'},
 {icon:ReceiptText,title:'Atendimento organizado',text:'Mesa, cliente ou comanda livre com histórico e responsável identificado.'},
 {icon:CreditCard,title:'Fiado sob controle',text:'Autorizações, limites, saldos e baixas para proteger o caixa e o relacionamento.'},
 {icon:UserCog,title:'Equipe com responsabilidade',text:'Gerentes e atendentes com acesso individual e rastreabilidade por conta.'},
 {icon:BarChart3,title:'Gestão com indicadores',text:'Faturamento, ticket médio, contas abertas, produtos e valores a receber em uma visão clara.'},
 {icon:ShieldCheck,title:'Estrutura para confiar',text:'Dados em nuvem, acessos individuais e uma operação construída para dar segurança ao proprietário.'}
];
const planItems=['PDV e comandas ilimitadas','Mesa, cliente ou comanda livre','Cadastro e histórico de clientes','Fiado / contas a receber','Produtos e preços','Dashboard e relatórios','Gerente e atendentes','Log de atendimento por conta','Personalização com sua marca','Acesso em nuvem','Suporte de implantação'];
function goApp(){window.history.pushState({},'','/app');window.dispatchEvent(new PopStateEvent('popstate'))}

export default function Landing(){
 const[menu,setMenu]=useState(false);
 return <div className="landing"><header className="lp-header"><a href="#inicio" className="lp-logo"><Brand/></a><nav className={menu?'lp-nav open':'lp-nav'}><a href="#beneficios">Soluções</a><a href="#operacao">Como funciona</a><a href="#indicadores">Gestão</a><a href="#plano">Planos</a><a href="#consultoria">Consultoria</a><button className="lp-login" onClick={goApp}>Área do cliente</button><a className="lp-cta small" href="#teste">Solicitar demonstração</a></nav><button className="lp-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main className="lp-main"><section className="lp-hero" id="inicio"><div className="hero-copy"><span className="lp-kicker"><ShieldCheck size={15}/> GESTÃO PROFISSIONAL PARA O SEU NEGÓCIO</span><h1>Mais controle.<br/>Mais confiança.<br/><em>Mais gestão.</em></h1><p className="hero-lead">Uma estrutura firme para organizar vendas, comandas, clientes, equipe e indicadores — com simplicidade para quem atende e visão para quem administra.</p><div className="hero-actions"><a className="lp-cta" href="#teste">Solicitar demonstração <ArrowRight size={18}/></a><a className="lp-secondary" href="#consultoria">Falar com um consultor</a></div><div className="hero-trust"><span><ShieldCheck/> Acesso individual</span><span><Check/> Implantação assistida</span><span><Headphones/> Suporte próximo</span></div></div><div className="hero-visual"><div className="glow"/><div className="app-window"><div className="window-top"><Brand light/><span className="window-status">OPERAÇÃO ONLINE</span></div><div className="mock-body"><aside><span className="active">Visão geral</span><span>Nova venda</span><span>Comandas</span><span>Clientes / Fiado</span><span>Usuários</span><span>Relatórios</span></aside><div className="mock-content"><div className="mock-title"><small>GESTÃO DO NEGÓCIO</small><strong>Visão geral</strong></div><div className="mock-metrics"><div><small>Faturamento</small><b>R$ 2.840</b><i>movimento do dia</i></div><div><small>Ticket médio</small><b>R$ 42,70</b><i>por conta</i></div><div><small>Fiado a receber</small><b>R$ 416</b><i>sob controle</i></div></div><div className="mock-chart"><div className="chart-head"><span>Vendas por hora</span><b>Hoje</b></div><div className="bars"><i/><i/><i/><i/><i/><i/><i/><i/></div></div></div></div></div><div className="floating-card fc-one"><ShieldCheck/><span><b>Operação rastreável</b><small>responsáveis identificados</small></span></div><div className="floating-card fc-two"><TrendingUp/><span><b>Gestão em tempo real</b><small>indicadores para decidir melhor</small></span></div></div></section>
 <section className="trust-band"><div><strong>Uma plataforma pensada para dar firmeza à operação.</strong><span>Controle de acesso</span><span>Rastreabilidade</span><span>Dados em nuvem</span><span>Implantação assistida</span><span>Suporte especializado</span></div></section>
 <section className="lp-section" id="beneficios"><div className="section-heading"><span className="lp-kicker">CONTROLE • SEGURANÇA • CREDIBILIDADE</span><h2>Seu negócio organizado sobre <em>uma base sólida.</em></h2><p>Menos improviso, mais clareza e processos bem definidos. O Meu Espetinho conecta atendimento, financeiro, clientes e equipe em uma experiência profissional e fácil de usar.</p></div><div className="benefit-grid">{benefits.map(({icon:Icon,title,text})=><article key={title}><span className="benefit-icon"><Icon/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="dark-section" id="operacao"><div className="dark-copy"><span className="lp-kicker">DO ATENDIMENTO À GESTÃO</span><h2>Simples para operar.<br/><em>Seguro para administrar.</em></h2><p>Cada venda segue um fluxo claro. A equipe ganha velocidade e o proprietário mantém controle sobre responsáveis, recebimentos e histórico.</p><div className="steps"><div><b>01</b><span><strong>Identifique</strong><small>Mesa, cliente ou comanda livre.</small></span></div><div><b>02</b><span><strong>Atenda</strong><small>Itens e responsável ficam registrados.</small></span></div><div><b>03</b><span><strong>Receba</strong><small>PIX, dinheiro, cartão ou fiado autorizado.</small></span></div><div><b>04</b><span><strong>Gerencie</strong><small>Histórico e indicadores apoiam decisões.</small></span></div></div></div><div className="phone-mock"><Brand light/><small>ATENDIMENTO EM ANDAMENTO</small><h3>Mesa 04</h3><div className="phone-products"><span>2× Espetinho de carne <b>R$ 20,00</b></span><span>2× Cerveja <b>R$ 16,00</b></span><span>1× Refrigerante <b>R$ 6,00</b></span></div><div className="phone-total"><span>Total</span><b>R$ 42,00</b></div><small>Responsável: Carlos</small><button>Receber e finalizar</button></div></section>
 <section className="lp-section" id="indicadores"><div className="section-heading"><span className="lp-kicker">INFORMAÇÃO PARA DECIDIR</span><h2>Gestão baseada em informação, <em>não em memória.</em></h2><p>Uma visão clara da operação para acompanhar vendas, pendências, clientes e equipe.</p></div><div className="benefit-grid"><article><span className="benefit-icon"><BarChart3/></span><h3>Faturamento e ticket médio</h3><p>Acompanhe movimento e valor médio das contas.</p></article><article><span className="benefit-icon"><ReceiptText/></span><h3>Contas abertas</h3><p>Veja atendimentos em andamento e valores pendentes.</p></article><article><span className="benefit-icon"><CreditCard/></span><h3>Fiado a receber</h3><p>Saldo por cliente, limite autorizado e baixas registradas.</p></article><article><span className="benefit-icon"><Users/></span><h3>Equipe identificada</h3><p>Saiba quem abriu, atendeu e fechou cada conta.</p></article><article><span className="benefit-icon"><TrendingUp/></span><h3>Produtos mais vendidos</h3><p>Entenda o giro e o que movimenta o seu caixa.</p></article><article><span className="benefit-icon"><ShieldCheck/></span><h3>Rastreabilidade</h3><p>Acessos individuais e histórico para uma gestão mais segura.</p></article></div></section>
 <section className="consulting-section" id="consultoria"><div><span className="lp-kicker">TECNOLOGIA QUE SE ADAPTA AO SEU NEGÓCIO</span><h2>Precisou ir além?<br/><em>Criamos soluções customizadas.</em></h2><p>Nem toda operação cabe em um sistema pronto. Nossa equipe pode estudar seu processo, identificar gargalos e desenvolver recursos, integrações e soluções digitais sob medida.</p><div className="consulting-points"><span><Check/> Diagnóstico da operação</span><span><Check/> Customizações e novos módulos</span><span><Check/> Integrações e automações</span><span><Check/> Evolução acompanhando o negócio</span></div></div><div className="consulting-card"><span className="consulting-label">CONSULTORIA ESPECIALIZADA</span><strong>Transforme uma necessidade operacional em uma solução prática.</strong><p>Conte como sua empresa trabalha e o que precisa melhorar. Avaliamos o cenário e desenhamos a solução mais adequada.</p><a className="lp-cta full" href="#teste">Solicitar consultoria <ArrowRight size={18}/></a></div></section>
 <section className="lp-section pricing-section" id="plano"><div className="section-heading"><span className="lp-kicker">INVESTIMENTO CLARO E PREVISÍVEL</span><h2>Comece com uma estrutura <em>profissional.</em></h2><p>Setup inicial de R$ 199 para configuração e implantação. Depois, R$ 89 por mês com até 3 usuários incluídos.</p></div><div className="pricing-wrap"><div className="price-card"><span className="popular">PLANO MEU ESPETINHO</span><div className="price"><small>R$</small><strong>89</strong><span>,00<br/><i>/mês</i></span></div><div className="activation"><span>Setup inicial</span><b>R$ 199,00</b><small>pagamento único</small></div><ul>{planItems.map(item=><li key={item}><Check/>{item}</li>)}</ul><div className="activation"><span>Usuários</span><b>até 3 incluídos</b><small>do 4º em diante: + R$ 39/mês por usuário</small></div><a className="lp-cta full" href="#teste">Solicitar demonstração <ArrowRight size={18}/></a></div><div className="value-copy"><span className="lp-kicker">POR QUE MEU ESPETINHO?</span><h3>Uma ferramenta para colocar <em>ordem, controle e visão</em> na rotina.</h3><div className="value-list"><div><span>OPERAÇÃO</span><b>Fluxo simples e padronizado.</b><small>Mais consistência no atendimento.</small></div><div><span>RELACIONAMENTO</span><b>Histórico por cliente.</b><small>Consumo e fiado em um só lugar.</small></div><div><span>EQUIPE</span><b>Responsabilidade registrada.</b><small>Gerentes e atendentes com login individual.</small></div><div><span>GESTÃO</span><b>Indicadores claros.</b><small>Informação para acompanhar e decidir.</small></div></div></div></div></section>
 <section className="lead-section" id="teste"><div><span className="lp-kicker">CONVERSE COM NOSSA EQUIPE</span><h2>Mais estrutura para o seu negócio. <em>Comece por uma conversa.</em></h2><p>Solicite uma demonstração do Meu Espetinho ou apresente sua necessidade para avaliarmos uma solução customizada.</p><div className="launch-badges"><span><Check/> Demonstração orientada</span><span><Check/> Implantação assistida</span><span><Check/> Consultoria e customização</span></div></div><LeadForm/></section>
 <section className="final-cta"><Brand light/><h2>Tecnologia confiável para uma gestão mais firme.</h2><p>Organização, controle e informação para sustentar o crescimento do seu negócio.</p><div className="hero-actions final-actions"><a className="lp-cta" href="#teste">Solicitar demonstração <ArrowRight/></a><a className="lp-secondary dark-alt" href="#consultoria">Solicitar consultoria</a></div><small>Meu Espetinho • Tecnologia e soluções pela GRIT</small></section></main><footer><Brand/><span>Meu Espetinho • Seu negócio no controle.</span><small>Soluções digitais, consultoria e desenvolvimento customizado.</small></footer></div>;
}
