import { FormEvent, useState } from 'react';
import { ArrowRight, CheckCircle2 } from 'lucide-react';

const endpoint = 'https://pcrwtoddavpvkaxwtstc.supabase.co/functions/v1/capture-lead';

export default function LeadForm({ compact = false }: { compact?: boolean }) {
  const [status,setStatus]=useState<'idle'|'sending'|'done'|'error'>('idle');
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus('sending');const form=new FormData(e.currentTarget);const q=new URLSearchParams(location.search);const payload={name:form.get('name'),whatsapp:form.get('whatsapp'),email:form.get('email'),business_name:form.get('business_name'),city:form.get('city'),source:q.get('utm_source')||'organic',campaign:q.get('utm_campaign'),medium:q.get('utm_medium'),content:q.get('utm_content'),landing_page:location.href};try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error();setStatus('done');}catch{setStatus('error')}}
  if(status==='done')return <div className="lead-success"><CheckCircle2/><div><strong>Cadastro recebido!</strong><span>Você já pode criar sua conta e iniciar o teste de 3 dias.</span><a className="lp-cta small" href="/cadastro">Criar conta grátis <ArrowRight size={16}/></a></div></div>;
  return <form className={compact?'lead-form compact':'lead-form'} onSubmit={submit}><input name="name" required placeholder="Seu nome"/><input name="business_name" placeholder="Nome do seu negócio"/><input name="whatsapp" required placeholder="WhatsApp com DDD" inputMode="tel"/>{!compact&&<><input name="email" type="email" placeholder="Seu melhor e-mail"/><input name="city" placeholder="Cidade / UF"/></>}<button className="lp-cta full" disabled={status==='sending'}>{status==='sending'?'Enviando...':'Quero testar por 3 dias'} <ArrowRight size={18}/></button>{status==='error'&&<small>Não foi possível enviar agora. Tente novamente.</small>}<small>Sem cartão. Seus dados serão usados apenas para atendimento do Meu Espetinho.</small></form>;
}