import { BarChart3, CheckCircle2, ClipboardList, CreditCard, Headphones, Package, Receipt, ShieldCheck, ShoppingCart, Smartphone, Store, Users, WalletCards, Zap } from 'lucide-react';
import { trackMarketing } from './lib/analytics';
import './marketing.css';

const features = [
  [Zap, 'Venda rápida e simples', 'Registre pedidos em poucos toques, sem complicar a rotina da equipe.'],
  [Receipt, 'Comanda digital', 'Controle por mesa, cliente ou número e feche a conta com histórico completo.'],
  [WalletCards, 'Caixa e recebimentos', 'Dinheiro, PIX, cartão e fiado organizados em um só lugar.'],
  [Users, 'Clientes e fiado', 'Cadastre clientes, acompanhe saldos e registre pagamentos com clareza.'],
  [Package, 'Produtos e estoque opcional', 'Use só o básico ou ative controle de estoque quando fizer sentido para o negócio.'],
  [ClipboardList, 'Lista de compras', 'O sistema analisa as vendas e sugere o que comprar para a próxima semana.'],
  [BarChart3, 'Indicadores fáceis', 'Veja faturamento, ticket médio, produtos vendidos e movimento sem planilhas.'],
  [ShieldCheck, 'Equipe e rastreabilidade', 'Acessos individuais para saber quem abriu, atendeu e fechou cada conta.'],
] as const;
const audiences=[['Espetinhos e churrasquinhos','Para quem vende no balcão, em mesas, por comanda ou em eventos.'],['Bares e botecos','Controle simples de pedidos, mesas, bebidas, fiado e fechamento de caixa.'],['Trailers e food trucks','PDV leve para operar pelo celular, tablet ou computador.'],['Barracas e pequenos restaurantes','Organização sem exigir conhecimento técnico ou rotina administrativa complexa.']];
const faq=[['Existe sistema para controlar vendas de espetinho pelo celular?','Sim. O Meu Espetinho funciona na web e pode ser usado pelo celular, tablet ou computador para registrar vendas, comandas, clientes, recebimentos e acompanhar a operação.'],['O sistema serve para churrasquinho, bar ou trailer?','Sim. A operação foi desenhada para pequenos negócios de alimentação, como espetinhos, churrasquinhos, bares, botecos, trailers, barracas e food trucks.'],['Preciso saber controlar estoque para usar?','Não. O estoque é opcional. Você pode começar apenas com vendas e comandas.'],['Dá para controlar fiado e clientes?','Sim. O sistema registra clientes, valores fiados, pagamentos, histórico e saldo a receber.'],['Consigo imprimir ou enviar a conta ao cliente?','Sim. No fechamento é possível gerar comprovante para impressora térmica e também uma imagem para compartilhar ou apresentar ao cliente.'],['Quanto custa o Meu Espetinho?','O plano mensal é de R$ 89,00 com até 3 usuários incluídos. O setup inicial é de R$ 199,00 para configuração e implantação assistida.']];
function tracked(name:string,params:Record<string,string>={}){trackMarketing({name,params});}

function PhoneMockups(){return <div className="phone-showcase" aria-label="Exemplos da operação do Meu Espetinho pelo celular">
 <div className="phone phone-sale"><div className="phone-notch"/><div className="phone-screen"><div className="phone-app-head"><img src="/favicon.svg" alt=""/><span><b>Meu Espetinho</b><small>Nova venda</small></span></div><div className="phone-search">Buscar produto...</div><div className="phone-products"><button><span>🥩</span><b>Espeto bovino</b><small>R$ 12,00</small></button><button><span>🍗</span><b>Frango</b><small>R$ 10,00</small></button><button><span>🥤</span><b>Refrigerante</b><small>R$ 6,00</small></button><button><span>🍺</span><b>Cerveja</b><small>R$ 8,00</small></button></div><div className="phone-cart"><span>3 itens</span><strong>R$ 34,00</strong><button>Adicionar à comanda</button></div></div></div>
 <div className="phone phone-checkout"><div className="phone-notch"/><div className="phone-screen"><div className="phone-app-head"><img src="/favicon.svg" alt=""/><span><b>Mesa 07</b><small>Fechar conta</small></span></div><div className="bill"><p><span>2× Espeto bovino</span><b>R$ 24,00</b></p><p><span>1× Refrigerante</span><b>R$ 6,00</b></p><p><span>1× Cerveja</span><b>R$ 8,00</b></p><hr/><p className="bill-total"><span>Total</span><strong>R$ 38,00</strong></p></div><small className="pay-label">Como recebeu?</small><div className="pay-grid"><button>PIX</button><button>Cartão</button><button>Dinheiro</button><button>Fiado</button></div><button className="finish-sale">Fechar conta</button></div></div>
 <div className="phone phone-dashboard"><div className="phone-notch"/><div className="phone-screen"><div className="phone-app-head"><img src="/favicon.svg" alt=""/><span><b>Visão do dono</b><small>Hoje</small></span></div><div className="dash-card"><small>Faturamento</small><strong>R$ 1.284,00</strong><span>acompanhe de onde estiver</span></div><div className="mini-kpis"><div><small>Pedidos</small><b>47</b></div><div><small>Ticket médio</small><b>R$ 27,32</b></div></div><div className="phone-bars"><i style={{height:'38%'}}/><i style={{height:'58%'}}/><i style={{height:'44%'}}/><i style={{height:'82%'}}/><i style={{height:'67%'}}/><i style={{height:'92%'}}/></div><div className="dash-note"><BarChart3/> Movimento por horário</div></div></div>
 </div>}

export default function Marketing(){const signup='/cadastro',appUrl='/app',consultUrl='/contato?assunto=consultoria';return <div className="marketing-page">
<header className="marketing-nav"><a className="marketing-brand" href="#inicio"><img src="/logo-meu-espetinho.svg" alt="Meu Espetinho — Seu negócio no controle"/></a><nav><a href="#celular">No celular</a><a href="#recursos">Recursos</a><a href="#planos">Plano</a><a href="#duvidas">Dúvidas</a></nav><a className="nav-login" href={appUrl}>Entrar</a><a className="cta small" href={signup} onClick={()=>tracked('trial_cta_click',{source:'header'})}>Testar 3 dias</a></header>
<main>
<section className="hero" id="inicio"><div className="hero-copy"><span className="hero-kicker">SEU ESPETINHO NA PALMA DA MÃO</span><h1>Venda, receba e acompanhe tudo <em>pelo celular.</em></h1><p className="hero-main">Do primeiro pedido ao fechamento da conta: sua equipe lança as vendas em poucos toques e você acompanha caixa, comandas e indicadores de onde estiver.</p><p className="hero-sub">Sem computador obrigatório. Sem caderninho. <strong>O celular vira sua ferramenta de gestão.</strong></p><div className="hero-actions"><a className="cta" href={signup} onClick={()=>tracked('trial_cta_click',{source:'hero_mobile'})}><Smartphone size={20}/> Testar grátis por 3 dias</a><a className="ghost" href="#celular">Ver funcionando no celular</a></div><div className="trust-row"><span><CheckCircle2/> Acesso rápido</span><span><ShieldCheck/> Dados em nuvem</span><span><Headphones/> Implantação assistida</span></div></div><div className="hero-visual"><PhoneMockups/></div></section>
<section className="credibility"><div><strong>Venda onde estiver</strong><span>Balcão, mesa, evento ou churrasqueira.</span></div><div><strong>Feche a conta na hora</strong><span>PIX, cartão, dinheiro ou fiado.</span></div><div><strong>Acompanhe pelo celular</strong><span>Vendas e indicadores na palma da mão.</span></div><div><strong>Sem equipamento caro</strong><span>Use o celular que você já tem.</span></div></section>
<section className="mobile-operation" id="celular"><div className="section-heading"><span className="section-kicker">90% DA ROTINA PODE ACONTECER NO CELULAR</span><h2>Da churrasqueira à gestão, sem precisar parar o negócio.</h2><p>Uma experiência pensada para toque, velocidade e telas pequenas. Abra a comanda, lance itens, receba e depois confira como foi o dia.</p></div><div className="mobile-benefits"><article><span>01</span><Smartphone/><h3>Lance a venda em poucos toques</h3><p>Pesquise ou toque no produto, ajuste a quantidade e mande direto para a comanda.</p></article><article><span>02</span><Receipt/><h3>Feche a conta na frente do cliente</h3><p>Confira os itens, escolha a forma de pagamento e finalize sem calculadora ou papel.</p></article><article><span>03</span><BarChart3/><h3>Veja o negócio mesmo longe</h3><p>Acompanhe faturamento, pedidos e ticket médio pelo celular, sem esperar o fim do dia.</p></article></div><div className="mobile-callout"><div><strong>Seu negócio cabe no bolso.</strong><p>Quem atende usa. Quem gerencia acompanha. Tudo na mesma operação.</p></div><a className="cta" href={signup} onClick={()=>tracked('trial_cta_click',{source:'mobile_section'})}>Quero testar no meu celular</a></div></section>
<section className="positioning" id="para-quem"><div className="section-heading"><span className="section-kicker">FEITO PARA O PEQUENO NEGÓCIO DE ALIMENTAÇÃO</span><h2>Um sistema que fala a língua de quem está no balcão.</h2><p>Troque caderno, papel, calculadora e planilhas por uma operação simples, acessível pelo navegador do celular.</p></div><div className="audience-grid">{audiences.map(([title,text])=><article key={title}><Store/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="feature-section" id="recursos"><div className="section-heading"><span className="section-kicker">O ESSENCIAL, BEM FEITO</span><h2>Controle sem complicar a operação.</h2><p>Comece pelas vendas e comandas. Ative mais controles conforme precisar.</p></div><div className="feature-strip">{features.map(([Icon,title,text])=><article key={title}><span className="feature-icon"><Icon/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="simple-flow" id="como-funciona"><div><span className="section-kicker">DA VENDA AO FECHAMENTO</span><h2>Quatro passos. Na palma da mão.</h2><p>O fluxo foi desenhado para reduzir cliques e manter o atendimento rápido.</p></div><ol><li><b>1</b><span><strong>Abra</strong><small>Mesa, cliente ou comanda livre.</small></span></li><li><b>2</b><span><strong>Venda</strong><small>Toque nos produtos e registre.</small></span></li><li><b>3</b><span><strong>Receba</strong><small>Dinheiro, PIX, cartão ou fiado.</small></span></li><li><b>4</b><span><strong>Acompanhe</strong><small>Veja seus indicadores no celular.</small></span></li></ol></section>
<section className="shopping-bonus"><div className="bonus-icon"><ClipboardList/></div><div><span className="section-kicker">BÔNUS OPERACIONAL</span><h2>Lista de compras para a semana.</h2><p>O sistema usa o histórico de vendas para ajudar na reposição. Você pode complementar com carvão, gelo, molhos, descartáveis e outros itens.</p></div><a className="ghost dark" href={signup} onClick={()=>tracked('trial_cta_click',{source:'shopping_list'})}>Quero testar</a></section>
<section className="pricing" id="planos"><div className="pricing-intro"><span className="section-kicker">INVESTIMENTO PREVISÍVEL</span><h2>Profissional para o negócio. Simples para o bolso.</h2><p>Implantação acompanhada, acesso pelo celular e uma mensalidade clara.</p></div><article className="price-card setup"><span>Implantação</span><strong><small>R$</small>199,00</strong><p>Pagamento único.</p><ul><li>Configuração inicial</li><li>Orientação de uso</li><li>Personalização da operação</li></ul></article><article className="price-card featured"><span>Meu Espetinho</span><strong><small>R$</small>89,00<small>/mês</small></strong><ul><li>Até 3 usuários incluídos</li><li>Vendas e comandas</li><li>Clientes e fiado</li><li>Caixa e indicadores</li><li>Lista de compras</li><li>Acesso pelo celular</li></ul><small className="extra-user">Usuário adicional: + R$ 39/mês</small><a className="cta full" href={signup} onClick={()=>tracked('pricing_cta_click',{source:'pricing'})}>Testar grátis por 3 dias</a></article></section>
<section className="faq" id="duvidas"><div className="section-heading"><span className="section-kicker">DÚVIDAS DE QUEM EMPREENDE</span><h2>Respostas rápidas antes de começar.</h2></div><div className="faq-grid">{faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
<section className="consulting"><div><span className="section-kicker">PRECISA DE ALGO DIFERENTE?</span><h2>A tecnologia acompanha o seu negócio.</h2><p>Se sua operação precisar de um fluxo específico, integração ou novo recurso, a GRIT pode avaliar.</p></div><a className="ghost dark" href={consultUrl}><Headphones size={20}/> Falar com a GRIT</a></section>
<section className="closing-cta"><div><img src="/logo-meu-espetinho.svg" alt="Meu Espetinho"/><h2>Seu negócio no controle. Onde você estiver.</h2><p>Abra no celular e comece a organizar sua operação.</p></div><div className="closing-actions"><a className="cta" href={signup} onClick={()=>tracked('trial_cta_click',{source:'footer'})}>Testar grátis por 3 dias</a><a className="ghost" href={appUrl}>Já sou cliente</a></div></section>
</main><footer><div><ShieldCheck/> Meu Espetinho</div><div>Seu negócio no controle.</div><div>Uma solução GRIT</div><div>© 2026</div></footer></div>}
