import { BarChart3, CheckCircle2, Headphones, Package, Receipt, ShieldCheck, ShoppingCart, Store, Users, WalletCards, Zap } from 'lucide-react';

const features = [
  [Zap, 'PDV rápido', 'Venda em segundos com poucos toques.'],
  [Receipt, 'Comandas', 'Controle por cliente, mesa ou número.'],
  [Package, 'Produtos', 'Preços, categorias e cardápio organizado.'],
  [BarChart3, 'Relatórios', 'Indicadores claros para decidir melhor.'],
  [WalletCards, 'Caixa', 'Entradas, saídas e fechamento organizado.'],
  [Users, 'Clientes', 'Histórico e relacionamento em um só lugar.'],
  [ShieldCheck, 'Equipe', 'Usuários, funções e rastreabilidade.'],
  [Store, 'Personalização', 'Sua operação configurada para seu negócio.'],
] as const;

const benefits = ['Lançamento rápido de vendas','Controle de contas abertas','Fechamento por forma de pagamento','Histórico de consumo por cliente','Relatórios e indicadores gerenciais','Funcionários com permissões','Personalização com sua marca','Funciona em celular, tablet e computador'];

export default function Marketing() {
  const appUrl='/app'; const consultUrl='/contato?assunto=consultoria';
  return <div className="marketing-page">
    <header className="marketing-nav"><a className="marketing-brand" href="#inicio"><img src="/logo-meu-espetinho.svg" alt="Meu Espetinho"/></a><nav><a href="#recursos">Soluções</a><a href="#beneficios">Benefícios</a><a href="#planos">Planos</a><a href="#consultoria">Consultoria</a></nav><a className="cta small" href={appUrl}>Acessar sistema</a></header>
    <main>
      <section className="hero" id="inicio"><div className="hero-copy"><div className="hero-logo"><img src="/logo-meu-espetinho.svg" alt="Meu Espetinho — seu negócio no controle"/></div><span className="hero-kicker">Tecnologia para uma operação mais firme</span><h1>Controle para vender.<br/><em>Estrutura para crescer.</em></h1><p>Uma plataforma de gestão criada para dar segurança à rotina do seu negócio. Organize vendas, comandas, equipe, clientes e resultados com informações claras e uma operação confiável.</p><div className="hero-actions"><a className="cta" href={appUrl}><ShoppingCart size={20}/> Conhecer o sistema</a><a className="ghost" href={consultUrl}><Headphones size={19}/> Solicitar consultoria</a></div><div className="trust-row"><span><ShieldCheck/> Dados protegidos</span><span><CheckCircle2/> Operação rastreável</span><span><CheckCircle2/> Suporte especializado</span></div></div><div className="hero-visual"><div className="glow"></div><div className="mock-window"><div className="mock-head"><span></span><span></span><span></span><b>Visão gerencial</b></div><div className="mock-metrics"><article><small>Faturamento hoje</small><strong>R$ 2.840,00</strong><em>+12%</em></article><article><small>Pedidos</small><strong>137</strong><em>+9%</em></article><article><small>Ticket médio</small><strong>R$ 20,73</strong></article><article><small>Contas abertas</small><strong>9 / R$ 416</strong></article></div><div className="mock-chart"><div><span style={{height:'28%'}}></span><span style={{height:'45%'}}></span><span style={{height:'62%'}}></span><span style={{height:'88%'}}></span><span style={{height:'70%'}}></span><span style={{height:'52%'}}></span></div><p>Vendas por horário</p></div></div><div className="skewer-card"><ShieldCheck/><div><b>Gestão com confiança</b><span>Informação, controle e rastreabilidade.</span></div></div></div></section>
      <section className="credibility"><div><strong>Sistema em nuvem</strong><span>Acesse sua operação onde estiver.</span></div><div><strong>Controle por usuário</strong><span>Saiba quem abriu, atendeu e fechou.</span></div><div><strong>Informação gerencial</strong><span>Indicadores para decisões mais seguras.</span></div><div><strong>Suporte humano</strong><span>Implantação e acompanhamento especializado.</span></div></section>
      <section className="feature-strip" id="recursos">{features.map(([Icon,title,text])=><article key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</section>
      <section className="benefits" id="beneficios"><div><span className="section-kicker">Confiança para a rotina</span><h2>Seu negócio organizado.<br/><em>Sua gestão mais segura.</em></h2><p>O Meu Espetinho centraliza a operação e reduz a dependência de controles soltos. Da abertura da comanda ao fechamento, você mantém histórico, responsáveis e informações importantes em um ambiente único.</p><div className="benefit-list">{benefits.map(item=><span key={item}><CheckCircle2/> {item}</span>)}</div></div><div className="report-card"><span>Gestão profissional</span><h3>Decida com informação.</h3><p>Tenha uma leitura clara da operação para acompanhar vendas, equipe, clientes e resultados.</p><div className="report-grid"><b>+ controle<small>rotina organizada</small></b><b>+ segurança<small>ações rastreáveis</small></b><b>+ agilidade<small>atendimento simples</small></b><b>+ visão<small>indicadores gerenciais</small></b></div></div></section>
      <section className="consulting" id="consultoria"><div><span className="section-kicker">Soluções sob medida</span><h2>Seu negócio tem uma necessidade específica?</h2><p>Além do Meu Espetinho, desenvolvemos soluções customizadas para operações que precisam de fluxos, indicadores, integrações ou controles próprios. Nossa consultoria entende o processo antes de propor tecnologia.</p></div><a className="cta" href={consultUrl}><Headphones size={20}/> Solicitar consultoria</a></section>
      <section className="pricing" id="planos"><div className="pricing-intro"><span className="section-kicker">Plano transparente</span><h2>Estrutura profissional com investimento previsível.</h2><p>Implantação acompanhada, sistema em nuvem e suporte para sua equipe começar com segurança.</p></div><article className="price-card light"><span>Setup inicial</span><strong><small>R$</small>199,00</strong><ul><li>Configuração inicial</li><li>Personalização da operação</li><li>Treinamento inicial</li><li>Suporte na implantação</li></ul></article><article className="price-card featured"><span>Plano mensal</span><strong><small>R$</small>89,00<small>/mês</small></strong><ul><li>Sistema completo</li><li>Até 3 usuários incluídos</li><li>Relatórios gerenciais</li><li>Atualizações contínuas</li><li>Backup em nuvem</li></ul><small className="extra-user">Usuário adicional: + R$ 39/mês</small><a className="cta full" href={appUrl}>Começar agora</a></article><article className="price-card trial"><span>Experimente</span><strong>3 dias</strong><p>Conheça o sistema e valide a rotina antes de contratar.</p><a className="cta full" href={appUrl}>Testar o sistema</a></article></section>
      <section className="closing-cta"><div><img src="/logo-meu-espetinho.svg" alt="Meu Espetinho"/><h2>Uma base mais firme para o seu negócio.</h2><p>Controle, informação e suporte para sua operação crescer com confiança.</p></div><div className="closing-actions"><a className="cta" href={appUrl}>Conhecer o Meu Espetinho</a><a className="ghost" href={consultUrl}>Solicitar consultoria</a></div></section>
    </main><footer><div><ShieldCheck/> Dados protegidos</div><div>Suporte especializado</div><div>Atualizações contínuas</div><div>© 2026 Meu Espetinho · Tecnologia GRIT</div></footer>
  </div>;
}
