import { CheckCircle2, Clock3, Receipt, Store, UserRound } from 'lucide-react';
import type { Order } from './store';

const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
const subtotal=(o:Order)=>o.items.reduce((s,i)=>s+i.qty*i.unitPrice,0);
function elapsed(iso:string){const mins=Math.max(0,Math.floor((Date.now()-new Date(iso).getTime())/60000));if(mins<60)return `${mins} min`;const h=Math.floor(mins/60),m=mins%60;return `${h}h${m?` ${m}m`:''}`}
function typeLabel(o:Order){return o.source==='table'?'Mesa':o.source==='customer'?'Cliente':'Comanda'}

export default function OpenAccountsDashboard({orders,serviceEnabled,servicePercent,onOpen,onNewSale}:{orders:Order[];serviceEnabled?:boolean;servicePercent:number;onOpen:(order:Order)=>void;onNewSale:()=>void}){
 const enabled=Boolean(serviceEnabled);const grand=(o:Order)=>{const base=subtotal(o);return base+(enabled?base*servicePercent/100:0)};const totalOpen=orders.reduce((s,o)=>s+grand(o),0);
 return <section className="panel open-accounts-panel"><div className="open-accounts-head"><div><span className="eyebrow">Agora no salão</span><h2>Contas em aberto</h2><p className="muted">Mesas, clientes e comandas livres com o valor parcial atualizado.</p></div><div className="open-accounts-total"><span>Total parcial em aberto</span><strong>{money(totalOpen)}</strong>{enabled&&<small className="dashboard-service-pill">+ {servicePercent}% serviço incluído</small>}</div></div>{!orders.length?<div className="open-accounts-empty"><CheckCircle2 size={30}/><strong>Nenhuma conta em aberto</strong><span>Seu salão está zerado. Abra a próxima venda quando o cliente chegar.</span><button className="primary" onClick={onNewSale}>+ Abrir nova conta</button></div>:<div className="open-accounts-grid">{orders.map(o=>{const base=subtotal(o);const fee=enabled?base*servicePercent/100:0;const Icon=o.source==='table'?Store:o.source==='customer'?UserRound:Receipt;return <button className="open-account-card" key={o.id} onClick={()=>onOpen(o)}><div className="open-account-top"><div className="open-account-id"><span className="open-account-icon"><Icon size={19}/></span><div><strong>{o.label}</strong><span>{typeLabel(o)} • {o.items.reduce((s,i)=>s+i.qty,0)} itens</span></div></div><span className="open-account-time"><Clock3 size={11}/> {elapsed(o.openedAt)}</span></div><div className="open-account-value"><div><small>Parcial da conta</small><strong>{money(base+fee)}</strong></div>{fee>0&&<small className="open-account-service">serviço {money(fee)}</small>}</div><div className="open-account-meta"><span>{o.assignedName||o.openedByName||'Equipe'}</span><strong>Abrir conta →</strong></div></button>})}</div>}</section>
}
