import { BarChart3, BookOpen, CheckCircle2, ClipboardList, Receipt, ShieldCheck, Smartphone, WalletCards } from 'lucide-react';import { trackMarketing } from './lib/analytics';import './marketing.css';
type Guide={slug:string,title:string,kicker:string,answer:string,steps:string[],cta:string,landing:string};
export const guides:Guide[]=[
{slug:'como-controlar-fiado-no-bar',title:'Como controlar fiado no bar sem depender do caderno',kicker:'CLIENTES E FIADO',answer:'O controle começa registrando cliente, valor, data e cada pagamento no mesmo lugar. Assim o saldo deixa de depender de memória, papel ou mensagens espalhadas.',steps:['Cadastre o cliente antes de lançar o fiado','Registre o valor junto com a venda','Baixe cada pagamento recebido','Consulte saldo e histórico antes de uma nova venda'],cta:'Quero controlar o fiado pelo celular',landing:'/controle-de-fiado'},
{slug:'como-organizar-comandas-de-mesa',title:'Como organizar comandas de mesa em um espetinho',kicker:'COMANDAS',answer:'Use uma identificação única por mesa ou cliente e registre cada item no momento do pedido. O fechamento fica mais rápido porque a conta já está consolidada.',steps:['Abra uma comanda por mesa ou cliente','Lance os produtos enquanto atende','Confira itens e quantidades antes de receber','Feche a conta e registre a forma de pagamento'],cta:'Quero testar a comanda digital',landing:'/comanda-digital-para-espetinho'},
{slug:'como-fazer-fechamento-de-caixa',title:'Como fazer o fechamento de caixa de um bar pequeno',kicker:'CAIXA',answer:'Separe as vendas por forma de pagamento e compare o que o sistema registra com dinheiro, PIX, cartão e fiado realmente recebidos.',steps:['Registre todas as vendas','Informe corretamente como cada conta foi paga','Confira totais por forma de pagamento','Analise diferenças antes de encerrar o dia'],cta:'Quero organizar meu caixa',landing:'/controle-de-caixa-para-espetinho'},
{slug:'como-controlar-estoque-de-bebidas',title:'Como controlar estoque de bebidas e produtos no bar',kicker:'ESTOQUE',answer:'Um estoque útil precisa acompanhar entrada, venda e saldo. Comece pelos itens que mais impactam a operação e amplie o controle conforme a rotina amadurece.',steps:['Cadastre os produtos principais','Registre o estoque inicial','Dê baixa a partir das vendas','Revise itens com saldo baixo antes da compra'],cta:'Quero melhorar meu estoque',landing:'/controle-de-estoque-para-bar'},
{slug:'como-administrar-espetinho-pelo-celular',title:'Como administrar um espetinho pelo celular',kicker:'GESTÃO MOBILE',answer:'Centralize pedidos, comandas, recebimentos, clientes e indicadores em uma ferramenta acessível pelo navegador do celular.',steps:['Use o celular no lançamento das vendas','Feche contas no próprio atendimento','Consulte clientes e fiado sem procurar cadernos','Acompanhe vendas e indicadores mesmo fora do estabelecimento'],cta:'Quero testar no meu celular',landing:'/pdv-para-espetinho'},
{slug:'como-calcular-ticket-medio',title:'Como calcular o ticket médio de um bar ou espetinho',kicker:'INDICADORES',answer:'Ticket médio é o faturamento do período dividido pela quantidade de pedidos. Ele ajuda a entender quanto cada atendimento gera, em média.',steps:['Escolha um período de análise','Some o faturamento do período','Conte os pedidos fechados','Divida faturamento pela quantidade de pedidos e compare a evolução'],cta:'Quero acompanhar meus indicadores',landing:'/relatorios-de-vendas-para-bar'}];
export function getGuide(path:string){const slug=path.replace(/^\/guias\//,'').replace(/\/$/,'');return guides.find(g=>g.slug===slug)||null}
export function GuidesHub(){return <div className="marketing-page"><header className="marketing-nav"><a className="marketing-brand" href="/"><img src="/logo-meu-espetinho-v3.svg" alt="Meu Espetinho"/></a><nav><a href="/">Plataforma</a><a href="#guias">Guias</a></nav><a className="cta small" href="/cadastro">Testar 3 dias</a></header><main><section className="positioning"><div className="section-heading"><span className="section-kicker">GUIAS MEU ESPETINHO</span><h1>Conteúdo prático para organizar e vender melhor.</h1><p>Respostas diretas para problemas reais de espetinhos, bares, churrasquinhos, trailers e pequenos negócios de alimentação.</p></div><div className="audience-grid" id="guias">{guides.map(g=><article key={g.slug}><BookOpen/><h3>{g.title}</h3><p>{g.answer}</p><a href={'/guias/'+g.slug}>Ler guia →</a></article>)}</div></section></main></div>}
export default function SeoGuide({guide}:{guide:Guide}){const icons=[Smartphone,Receipt,WalletCards,ClipboardList];return <div className="marketing-page"><header className="marketing-nav"><a className="marketing-brand" href="/"><img src="/logo-meu-espetinho-v3.svg" alt="Meu Espetinho"/></a><nav><a href="/guias">Guias</a><a href={guide.landing}>Ver solução</a></nav><a className="cta small" href="/cadastro" onClick={()=>trackMarketing({name:'trial_cta_click',params:{source:'seo_guide',guide:guide.slug}})}>Testar 3 dias</a></header><main><section className="positioning"><div className="section-heading"><span className="section-kicker">{guide.kicker}</span><h1>{guide.title}</h1><p>{guide.answer}</p></div><div className="mobile-benefits">{guide.steps.map((s,i)=>{const Icon=icons[i%icons.length];return <article key={s}><span>0{i+1}</span><Icon/><h3>{s}</h3><p>Uma etapa simples para tornar a rotina mais organizada e rastreável.</p></article>})}</div><div className="mobile-callout"><div><strong>Faça isso sem voltar para o caderno.</strong><p>O Meu Espetinho reúne a operação em uma experiência simples para celular.</p></div><a className="cta" href="/cadastro" onClick={()=>trackMarketing({name:'trial_cta_click',params:{source:'seo_guide_bottom',guide:guide.slug}})}>{guide.cta}</a></div></section><section className="feature-section"><div className="section-heading"><span className="section-kicker">CONTINUE APRENDENDO</span><h2>Veja também a solução relacionada.</h2><p><a href={guide.landing}>Conhecer o recurso do Meu Espetinho →</a></p></div></section></main><footer><div><ShieldCheck/> Meu Espetinho</div><div>Guias para pequenos negócios.</div><div>Uma solução GRIT</div><div>© 2026</div></footer></div>}
