import { ArrowRight, BookOpen, Check, MessageCircle } from 'lucide-react';
import './landing-brand.css';
import './landing-conversion-v3.css';

type Guide={slug:string;title:string;description:string;eyebrow:string;intro:string;steps:string[];questions:[string,string][];landing:string};

export const guides:Guide[]=[
{slug:'como-calcular-custo-do-pao-frances',title:'Como calcular o custo do pão francês na padaria',description:'Entenda como organizar ingredientes, rendimento e custo unitário do pão francês para tomar decisões de preço com mais segurança.',eyebrow:'CUSTO E PRECIFICAÇÃO',intro:'O custo do pão francês começa na ficha técnica: farinha, fermento, sal, melhoradores, água, energia e perdas precisam ser analisados junto com o rendimento real da produção.',steps:['Padronize a receita e o rendimento por fornada','Registre o custo atualizado dos ingredientes','Considere perdas e variação de rendimento','Calcule o custo unitário antes de revisar o preço'],questions:[['Por que o rendimento da receita importa?','Porque o custo por unidade depende de quantos pães a receita realmente entrega. Uma diferença de rendimento altera diretamente o custo unitário.'],['Devo usar apenas o custo da farinha?','Não. Farinha é importante, mas outros ingredientes, perdas e custos diretamente ligados à produção também precisam entrar na análise.']],landing:'/sistema-para-padaria'},
{slug:'como-calcular-cmv-de-padaria',title:'Como calcular o CMV de uma padaria',description:'Aprenda a organizar custo de mercadorias vendidas, faturamento e margem para entender melhor o resultado da padaria.',eyebrow:'CMV E RESULTADO',intro:'O CMV ajuda a mostrar quanto os produtos vendidos consumiram em custo. Ele fica mais útil quando custos, vendas e estoque são registrados de forma consistente.',steps:['Defina o período que será analisado','Organize o custo dos produtos vendidos','Compare o CMV com o faturamento do mesmo período','Acompanhe a evolução da margem e dos principais produtos'],questions:[['CMV é a mesma coisa que despesa?','Não. CMV está ligado ao custo dos produtos vendidos. Aluguel, salários e outras despesas operacionais pertencem a outras categorias da gestão.'],['Por que acompanhar CMV por período?','Porque comparar períodos ajuda a identificar mudanças de custo, preço, mix e desperdício.']],landing:'/controle-de-estoque'},
{slug:'como-reduzir-desperdicio-na-padaria',title:'Como reduzir desperdício em uma padaria',description:'Veja como produção, estoque e histórico de vendas podem ajudar a reduzir sobras e perdas sem prejudicar o atendimento.',eyebrow:'PERDAS E PRODUÇÃO',intro:'Reduzir desperdício exige observar o que foi produzido, o que vendeu e o que sobrou. O objetivo não é produzir menos a qualquer custo, mas produzir com mais informação.',steps:['Registre as principais perdas e sobras','Compare produção com vendas por faixa de horário','Revise itens de baixo giro','Ajuste produção e compras usando histórico real'],questions:[['Toda sobra significa erro?','Não necessariamente. Alguma margem operacional pode existir, mas sobras recorrentes e sem medição dificultam saber onde o resultado está sendo perdido.'],['Estoque ajuda a reduzir desperdício?','Ajuda quando entradas, saídas e saldos são registrados com disciplina e usados no planejamento de compras e produção.']],landing:'/controle-de-estoque'},
{slug:'como-controlar-producao-de-padaria',title:'Como organizar o controle de produção de uma padaria',description:'Organize produção por item, quantidade e horário para aproximar a rotina da demanda real e reduzir improvisos.',eyebrow:'PRODUÇÃO',intro:'O controle de produção deve ser simples o suficiente para a equipe usar e detalhado o bastante para permitir comparação entre quantidade produzida, vendas e sobras.',steps:['Liste os itens críticos de produção diária','Defina quantidades e horários de referência','Registre produção e sobras','Compare com vendas e ajuste o planejamento'],questions:[['Preciso controlar todos os produtos de uma vez?','Não. Começar pelos itens de maior giro ou maior impacto costuma tornar a implantação mais viável.'],['Qual o papel do histórico de vendas?','Ele ajuda a transformar percepção de movimento em uma referência concreta para planejar quantidades.']],landing:'/sistema-para-padaria'},
{slug:'como-fazer-fechamento-de-caixa-na-padaria',title:'Como fazer o fechamento de caixa da padaria',description:'Aprenda a conferir vendas, dinheiro, PIX, cartão, fiado e despesas para fechar o caixa com mais clareza.',eyebrow:'CAIXA',intro:'Um fechamento confiável começa no registro correto das vendas durante o dia. Depois, cada forma de pagamento deve ser comparada com o valor efetivamente recebido.',steps:['Registre todas as vendas e formas de pagamento','Separe despesas e retiradas do caixa','Confira dinheiro, PIX e cartões','Analise diferenças antes de encerrar o período'],questions:[['Fiado entra no mesmo controle?','A venda deve ficar registrada, mas o valor a receber precisa ser separado do dinheiro efetivamente recebido.'],['Por que registrar despesas do caixa?','Porque retiradas não registradas dificultam entender diferenças no fechamento e prejudicam a análise do resultado.']],landing:'/controle-de-caixa'},
{slug:'como-controlar-fiado-na-padaria',title:'Como controlar fiado na padaria sem depender do caderno',description:'Organize clientes, vendas fiadas, pagamentos e saldos para diminuir erros e facilitar a cobrança.',eyebrow:'CLIENTES E FIADO',intro:'O fiado fica mais seguro quando cada venda é vinculada ao cliente certo e cada pagamento atualiza o saldo. O histórico reduz a dependência de memória e anotações dispersas.',steps:['Cadastre o cliente antes da venda fiada','Registre valor e data da compra','Baixe cada pagamento recebido','Consulte o saldo antes de liberar novas compras'],questions:[['O que deve constar no controle?','No mínimo cliente, data, valor da venda, pagamentos e saldo atual.'],['Posso usar WhatsApp para cobrança?','O WhatsApp pode facilitar o contato, desde que a comunicação seja respeitosa e o saldo esteja corretamente registrado.']],landing:'/controle-de-fiado'},
{slug:'como-precificar-produtos-de-padaria',title:'Como precificar produtos de padaria com mais segurança',description:'Entenda como custo, rendimento, margem e despesas influenciam a formação de preço em produtos de padaria.',eyebrow:'PREÇO E MARGEM',intro:'Preço não deve ser definido apenas olhando o concorrente. É necessário conhecer o custo do produto, rendimento da receita e margem necessária para contribuir com a operação.',steps:['Calcule o custo unitário do produto','Considere rendimento e perdas da receita','Defina uma margem coerente com a operação','Revise o preço quando os custos mudarem'],questions:[['Posso copiar o preço do concorrente?','O concorrente é uma referência de mercado, mas copiar o preço sem conhecer seu próprio custo pode comprometer a margem.'],['Quando devo revisar preços?','Sempre que houver mudanças relevantes nos custos, rendimento, embalagem, impostos ou estratégia comercial.']],landing:'/sistema-para-padaria'},
{slug:'como-organizar-estoque-de-padaria',title:'Como organizar o estoque de uma padaria',description:'Crie uma rotina simples para controlar farinha, ingredientes, bebidas, embalagens e produtos de revenda.',eyebrow:'ESTOQUE E COMPRAS',intro:'Um estoque eficiente combina cadastro, entrada, saída, saldo e estoque mínimo. Começar pelos itens de maior impacto reduz a complexidade e melhora a qualidade das informações.',steps:['Cadastre os itens mais importantes','Registre entradas de compra','Associe saídas ao consumo ou venda','Defina mínimos e faça conferências periódicas'],questions:[['Quais itens controlar primeiro?','Itens de maior giro, maior valor ou que causam impacto forte quando faltam são bons candidatos.'],['Estoque mínimo resolve sozinho?','Não. Ele funciona melhor quando o saldo registrado é confiável e a equipe mantém as movimentações atualizadas.']],landing:'/controle-de-estoque'}
];

export function getGuide(path:string){const slug=path.replace(/^\/guias\//,'').replace(/\/$/,'');return guides.find(g=>g.slug===slug)||null}

function Header(){const wa='https://wa.me/5585921716546?text='+encodeURIComponent('Olá! Vim por um guia do Sr. Padeiro e quero conhecer o sistema.');return <header className="sp-header"><div className="sp-header-inner"><a className="sp-logo" href="/"><img src="/sr-padeiro-logo.svg" alt="Sr. Padeiro"/></a><div className="sp-header-actions"><a className="sp-whatsapp-link" href={wa}><MessageCircle size={17}/> WhatsApp</a><a className="sp-primary small" href="/#lead">Teste grátis 7 dias</a></div></div></header>}

export function GuidesHub(){document.title='Guias para Padarias e Pequenos Comércios | Sr. Padeiro';return <div className="sp-landing"><Header/><main><section className="sp-section"><div className="sp-container"><div className="sp-section-head"><span>GUIAS SR. PADEIRO</span><h1>Conteúdo prático para controlar melhor a padaria.</h1><p>Custos, CMV, estoque, produção, caixa, fiado, desperdício e precificação explicados de forma objetiva para o pequeno empreendedor.</p></div><div className="sp-benefits-grid">{guides.map(g=><article key={g.slug}><BookOpen/><h3>{g.title}</h3><p>{g.intro}</p><a href={'/guias/'+g.slug}>Ler guia →</a></article>)}</div></div></section></main></div>}

export default function SeoGuide({guide}:{guide:Guide}){document.title=guide.title+' | Sr. Padeiro';let meta=document.querySelector('meta[name="description"]');if(!meta){meta=document.createElement('meta');meta.setAttribute('name','description');document.head.appendChild(meta)}meta.setAttribute('content',guide.description);let canonical=document.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.setAttribute('rel','canonical');document.head.appendChild(canonical)}canonical.setAttribute('href','https://srpadeiro.gritnews.com.br/guias/'+guide.slug);const related=guides.filter(g=>g.slug!==guide.slug).slice(0,3);return <div className="sp-landing"><Header/><main><section className="sp-hero"><div className="sp-container sp-hero-grid"><div className="sp-hero-copy"><span className="sp-eyebrow">{guide.eyebrow}</span><h1>{guide.title}</h1><p>{guide.intro}</p><div className="sp-hero-actions"><a className="sp-primary" href={guide.landing}>Conhecer a solução <ArrowRight size={18}/></a></div></div><div className="sp-benefit-card"><BookOpen/><b>Passo a passo</b>{guide.steps.map(x=><span key={x}><Check/>{x}</span>)}</div></div></section><section className="sp-section sp-soft"><div className="sp-container"><div className="sp-section-head"><span>COMO COMEÇAR</span><h2>Transforme informação em rotina de gestão.</h2></div><div className="sp-benefits-grid">{guide.steps.map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>Use esta etapa como referência e adapte o processo à realidade da sua operação.</p></article>)}</div></div></section><section className="sp-section"><div className="sp-container"><div className="sp-section-head"><span>DÚVIDAS FREQUENTES</span><h2>Respostas objetivas sobre o tema.</h2></div>{guide.questions.map(([q,a])=><article key={q} style={{maxWidth:900,margin:'0 auto 18px'}}><h3>{q}</h3><p>{a}</p></article>)}</div></section><section className="sp-section sp-soft"><div className="sp-container"><div className="sp-section-head"><span>CONTINUE APRENDENDO</span><h2>Outros guias para melhorar a gestão.</h2></div><div className="sp-benefits-grid">{related.map(g=><article key={g.slug}><h3>{g.title}</h3><p>{g.description}</p><a href={'/guias/'+g.slug}>Ler guia →</a></article>)}</div><div className="sp-hero-actions" style={{justifyContent:'center'}}><a className="sp-primary" href="/#lead">Quero testar o Sr. Padeiro <ArrowRight size={18}/></a></div></div></section></main></div>}
