import { useEffect,useState } from 'react';
import { CreditCard } from 'lucide-react';
import { supabase } from './lib/supabase';
import { track } from './lib/tracking';

export default function SubscriptionCard({orgId,compact=false}:{orgId:string;compact?:boolean}){
  const [status,setStatus]=useState<string|null>(null);const [activationPaid,setActivationPaid]=useState(false);const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState('');const [asaasReady,setAsaasReady]=useState(false);
  useEffect(()=>{Promise.all([supabase.from('srp_subscriptions').select('status').eq('organization_id',orgId).maybeSingle(),supabase.from('srp_organizations').select('activation_paid_at').eq('id',orgId).maybeSingle(),supabase.functions.invoke('asaas-health',{body:{}})]).then(([subscription,org,health])=>{setStatus(subscription.data?.status||null);setActivationPaid(Boolean(org.data?.activation_paid_at));setAsaasReady(Boolean(health.data?.configured))})},[orgId]);
  async function checkout(kind:'activation'|'subscription',provider:'asaas'|'mercadopago'){setBusy(provider);setMessage('');const activation=kind==='activation';track('begin_checkout',{product:'sr-padeiro',kind,provider,plan:activation?'sr_padeiro_activation_199':'sr_padeiro_89',value:activation?199:89,currency:'BRL'});const fn=provider==='asaas'?'create-asaas-checkout':activation?'create-srp-activation-checkout':'create-srp-subscription';const {data,error}=await supabase.functions.invoke(fn,{body:{organization_id:orgId,kind}});if(error||!data?.checkout_url){const code=data?.error||'';setMessage(code.includes('not_configured')?'Esta forma de pagamento está em configuração. Escolha a outra opção ou fale com a GRIT.':code==='activation_required'?'Conclua primeiro a implantação de R$ 199.':'Não foi possível abrir o pagamento agora.');setBusy(null);return}location.href=data.checkout_url}
  if(status==='active')return <section className={compact?'subscription-card compact':'subscription-card'}><CreditCard/><div><strong>Plano ativo</strong><p>Sr. Padeiro — R$ 89/mês</p></div></section>;
  const kind=activationPaid?'subscription':'activation';
  return <section className={compact?'subscription-card compact':'subscription-card'}><CreditCard/><div><strong>{activationPaid?'Ative sua mensalidade':'Implantação do Sr. Padeiro'}</strong><p>{activationPaid?'Assinatura de R$ 89/mês. Escolha a forma de pagamento mais conveniente.':'Pagamento único de R$ 199. Depois, conclua a assinatura mensal de R$ 89.'}</p>{status&&<small>Status atual: {status}</small>}</div><div className="payment-provider-actions"><button className="btn-orange" disabled={Boolean(busy)||!asaasReady} onClick={()=>checkout(kind,'asaas')}>{busy==='asaas'?'Abrindo...':asaasReady?(activationPaid?'Assinar no cartão — R$ 89/mês':'Pix ou cartão — sem conta'):'Pagamento direto em configuração'}</button><button className="btn-outline" disabled={Boolean(busy)} onClick={()=>checkout(kind,'mercadopago')}>{busy==='mercadopago'?'Abrindo...':'Pagar com Mercado Pago'}</button></div>{message&&<p className="subscription-message">{message}</p>}</section>
}
