import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, Boxes, Download, Home, LogOut, Menu, MessageCircle, Package, Plus, Search, Settings, ShoppingCart, Store, UserRound, WalletCards, X } from 'lucide-react';
import { supabase } from './lib/supabase';

type Role='owner'|'manager'|'cashier'|'stockist'|'viewer';
type Product={id:string;name:string;barcode:string|null;unit:string;sale_price:number;cost_price:number|null;active:boolean};
type Inventory={product_id:string;quantity:number;minimum_quantity:number};
type CartItem={product:Product;quantity:number};
type Brand={name:string;logo_url:string|null;primary_color:string|null;phone:string|null};
type Receipt={saleId?:string;items:CartItem[];total:number;payment:string;brand:Brand};

type Props={orgId:string;userId:string;role:Role;access:string;firstName:string;onSignOut:()=>void};
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export default function Workspace({orgId,userId,role,access,firstName,onSignOut}:Props){
  const [tab,setTab]=useState<'home'|'sell'|'products'|'cash'|'more'>('home');
  const [storeId,setStoreId]=useState<string|null>(null); const [brand,setBrand]=useState<Brand>({name:'Sr. Padeiro',logo_url:null,primary_color:'#F47A20',phone:null});
  const [products,setProducts]=useState<Product[]>([]); const [inventory,setInventory]=useState<Inventory[]>([]); const [todayTotal,setTodayTotal]=useState(0); const [todayCount,setTodayCount]=useState(0);
  const [openCash,setOpenCash]=useState<any>(null); const [message,setMessage]=useState(''); const [receipt,setReceipt]=useState<Receipt|null>(null);
  const canSell=['owner','manager','cashier'].includes(role); const canCatalog=['owner','manager','stockist'].includes(role); const canCash=['owner','manager','cashier'].includes(role); const canBrand=['owner','manager'].includes(role);

  async function load(){
    const day=new Date(); day.setHours(0,0,0,0);
    const [stores,org,prods,inv,sales,cash]=await Promise.all([
      supabase.from('srp_stores').select('id').eq('organization_id',orgId).eq('active',true).limit(1).maybeSingle(),
      supabase.from('srp_organizations').select('name,logo_url,primary_color,phone').eq('id',orgId).single(),
      supabase.from('srp_products').select('id,name,barcode,unit,sale_price,cost_price,active').eq('organization_id',orgId).eq('active',true).order('name'),
      supabase.from('srp_inventory').select('product_id,quantity,minimum_quantity').eq('organization_id',orgId),
      supabase.from('srp_sales').select('total').eq('organization_id',orgId).eq('status','completed').gte('created_at',day.toISOString()),
      supabase.from('srp_cash_registers').select('*').eq('organization_id',orgId).eq('status','open').order('opened_at',{ascending:false}).limit(1).maybeSingle()
    ]);
    if(stores.data?.id)setStoreId(stores.data.id); if(org.data)setBrand(org.data as Brand); setProducts((prods.data||[]) as Product[]); setInventory((inv.data||[]) as Inventory[]); setTodayTotal((sales.data||[]).reduce((s:any,v:any)=>s+Number(v.total),0)); setTodayCount((sales.data||[]).length); setOpenCash(cash.data||null);
  }
  useEffect(()=>{load()},[orgId]);
  const lowStock=useMemo(()=>inventory.filter(i=>Number(i.quantity)<=Number(i.minimum_quantity)).length,[inventory]);
  const ticket=todayCount?todayTotal/todayCount:0;

  return <div className="app-shell" style={{'--brand':brand.primary_color||'#F47A20'} as any}>
    <header className="topbar"><div className="workspace-brand">{brand.logo_url?<img src={brand.logo_url} alt={brand.name}/>:<div className="brand-mark">SP</div>}<div><span className="eyebrow">{brand.name} • {access}</span><h1>Bom dia, {firstName} 👋</h1></div></div><button className="icon-button" onClick={onSignOut} title="Sair"><LogOut size={19}/></button></header>
    {message&&<div className="workspace-message">{message}<button onClick={()=>setMessage('')}><X size={15}/></button></div>}
    <main className="content">
      {tab==='home'&&<HomeView total={todayTotal} count={todayCount} ticket={ticket} lowStock={lowStock} cash={openCash} onSell={()=>canSell&&setTab('sell')}/>} 
      {tab==='sell'&&<SellView orgId={orgId} storeId={storeId} userId={userId} products={products} inventory={inventory} cash={openCash} brand={brand} disabled={!canSell} onDone={(r)=>{setReceipt(r);load();setMessage('Venda concluída com sucesso.')}}/>}
      {tab==='products'&&<ProductsView orgId={orgId} storeId={storeId} products={products} inventory={inventory} editable={canCatalog} onChange={load} setMessage={setMessage}/>} 
      {tab==='cash'&&<CashView orgId={orgId} storeId={storeId} userId={userId} cash={openCash} enabled={canCash} onChange={load} setMessage={setMessage}/>} 
      {tab==='more'&&<MoreView orgId={orgId} role={role} brand={brand} editable={canBrand} onChange={load} setMessage={setMessage}/>} 
      {receipt&&<ReceiptModal receipt={receipt} onClose={()=>setReceipt(null)}/>} 
    </main>
    <nav className="bottom-nav" aria-label="Navegação principal"><Nav active={tab==='home'} onClick={()=>setTab('home')} icon={<Home size={20}/>} label="Início"/><Nav active={tab==='sell'} disabled={!canSell} onClick={()=>setTab('sell')} icon={<ShoppingCart size={20}/>} label="Vender"/><Nav active={tab==='products'} onClick={()=>setTab('products')} icon={<Package size={20}/>} label="Produtos"/><Nav active={tab==='cash'} disabled={!['owner','manager','cashier','viewer'].includes(role)} onClick={()=>setTab('cash')} icon={<WalletCards size={20}/>} label="Caixa"/><Nav active={tab==='more'} onClick={()=>setTab('more')} icon={<Menu size={20}/>} label="Mais"/></nav>
  </div>
}

function Nav({active,onClick,icon,label,disabled=false}:{active:boolean;onClick:()=>void;icon:any;label:string;disabled?:boolean}){return <button className={active?'active':''} disabled={disabled} onClick={onClick}>{icon}<span>{label}</span></button>}

function HomeView({total,count,ticket,lowStock,cash,onSell}:{total:number;count:number;ticket:number;lowStock:number;cash:any;onSell:()=>void}){return <><section className="hero-card"><span>Vendas de hoje</span><strong>{money(total)}</strong><small>{count?`${count} transações realizadas`:'Comece sua primeira venda'}</small></section><button className="primary-action" onClick={onSell}><Plus size={20}/> Nova venda</button><section className="grid"><article className="metric-card"><WalletCards size={22}/><span>Caixa</span><strong>{cash?'Aberto':'Fechado'}</strong></article><article className="metric-card warning"><AlertTriangle size={22}/><span>Estoque</span><strong>{lowStock} alertas</strong></article></section><section className="summary"><div className="section-title"><h2>Resumo do dia</h2></div><div className="summary-row"><span>Vendas</span><strong>{money(total)}</strong></div><div className="summary-row"><span>Transações</span><strong>{count}</strong></div><div className="summary-row"><span>Ticket médio</span><strong>{money(ticket)}</strong></div></section></>}

function ProductsView({orgId,storeId,products,inventory,editable,onChange,setMessage}:{orgId:string;storeId:string|null;products:Product[];inventory:Inventory[];editable:boolean;onChange:()=>void;setMessage:(v:string)=>void}){
  const [open,setOpen]=useState(false); const [name,setName]=useState(''); const [price,setPrice]=useState(''); const [cost,setCost]=useState(''); const [unit,setUnit]=useState('UN'); const [qty,setQty]=useState('0'); const [min,setMin]=useState('0'); const [search,setSearch]=useState('');
  const stock=new Map(inventory.map(i=>[i.product_id,i])); const list=products.filter(p=>p.name.toLowerCase().includes(search.toLowerCase()));
  async function submit(e:FormEvent){e.preventDefault();if(!storeId)return setMessage('Loja principal não encontrada.'); const p=await supabase.from('srp_products').insert({organization_id:orgId,name,sale_price:Number(price),cost_price:cost?Number(cost):null,unit}).select('id').single(); if(p.error)return setMessage(p.error.message); const inv=await supabase.from('srp_inventory').insert({organization_id:orgId,store_id:storeId,product_id:p.data.id,quantity:Number(qty),minimum_quantity:Number(min)}); if(inv.error)return setMessage(inv.error.message); setName('');setPrice('');setCost('');setQty('0');setMin('0');setOpen(false);setMessage('Produto cadastrado.');onChange()}
  return <section className="workspace-section"><div className="workspace-title"><div><span className="eyebrow">Catálogo e estoque</span><h2>Produtos</h2></div>{editable&&<button className="btn-orange" onClick={()=>setOpen(!open)}><Plus size={17}/> Novo</button>}</div><label className="search-box"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar produto"/></label>{open&&<form className="module-form" onSubmit={submit}><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do produto"/><input required type="number" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Preço de venda"/><input type="number" step="0.01" value={cost} onChange={e=>setCost(e.target.value)} placeholder="Custo (opcional)"/><select value={unit} onChange={e=>setUnit(e.target.value)}><option>UN</option><option>KG</option><option>G</option><option>L</option><option>ML</option><option>PACOTE</option><option>CAIXA</option></select><input type="number" step="0.001" value={qty} onChange={e=>setQty(e.target.value)} placeholder="Estoque inicial"/><input type="number" step="0.001" value={min} onChange={e=>setMin(e.target.value)} placeholder="Estoque mínimo"/><button className="btn-dark">Salvar produto</button></form>}<div className="product-list">{list.map(p=>{const i=stock.get(p.id);return <article key={p.id}><div><b>{p.name}</b><span>{p.unit} • {money(Number(p.sale_price))}</span></div><div className={Number(i?.quantity||0)<=Number(i?.minimum_quantity||0)?'stock-low':''}><b>{Number(i?.quantity||0).toLocaleString('pt-BR')}</b><span>em estoque</span></div></article>})}</div></section>
}

function SellView({orgId,storeId,userId,products,inventory,cash,brand,disabled,onDone}:{orgId:string;storeId:string|null;userId:string;products:Product[];inventory:Inventory[];cash:any;brand:Brand;disabled:boolean;onDone:(r:Receipt)=>void}){
  const [cart,setCart]=useState<CartItem[]>([]); const [search,setSearch]=useState(''); const [payment,setPayment]=useState('pix'); const [loading,setLoading]=useState(false); const stock=new Map(inventory.map(i=>[i.product_id,Number(i.quantity)]));
  const list=products.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())||(p.barcode||'').includes(search)); const total=cart.reduce((s,i)=>s+Number(i.product.sale_price)*i.quantity,0);
  function add(p:Product){setCart(c=>{const x=c.find(i=>i.product.id===p.id);return x?c.map(i=>i.product.id===p.id?{...i,quantity:i.quantity+1}:i):[...c,{product:p,quantity:1}]})}
  function qty(id:string,delta:number){setCart(c=>c.map(i=>i.product.id===id?{...i,quantity:Math.max(.001,i.quantity+delta)}:i).filter(i=>i.quantity>0))}
  const text=()=>`${brand.name}\n${cart.map(i=>`${i.quantity}x ${i.product.name} - ${money(i.quantity*Number(i.product.sale_price))}`).join('\n')}\nTOTAL: ${money(total)}`;
  function share(){window.open(`https://api.whatsapp.com/send?text=${encodeURIComponent(text())}`,'_blank','noopener,noreferrer')}
  async function finish(){if(disabled||!storeId||!cart.length)return;setLoading(true); const sale=await supabase.from('srp_sales').insert({organization_id:orgId,store_id:storeId,cash_register_id:cash?.id||null,seller_id:userId,subtotal:total,discount:0,total,status:'completed'}).select('id').single(); if(sale.error){setLoading(false);return}
    const items=cart.map(i=>({organization_id:orgId,sale_id:sale.data.id,product_id:i.product.id,quantity:i.quantity,unit_price:Number(i.product.sale_price),total:i.quantity*Number(i.product.sale_price)})); const itemRes=await supabase.from('srp_sale_items').insert(items); if(itemRes.error){setLoading(false);return}
    const pay=await supabase.from('srp_sale_payments').insert({organization_id:orgId,sale_id:sale.data.id,method:payment,amount:total}); if(pay.error){setLoading(false);return}
    await supabase.from('srp_operation_events').insert({organization_id:orgId,store_id:storeId,user_id:userId,event_name:'sale_completed',entity_type:'sale',entity_id:sale.data.id,metadata:{total,payment,items:cart.length}}); setLoading(false);onDone({saleId:sale.data.id,items:cart,total,payment,brand});setCart([])}
  return <section className="workspace-section"><div className="workspace-title"><div><span className="eyebrow">PDV</span><h2>Nova venda</h2></div><span className="role-chip">{cash?'Caixa aberto':'Caixa não obrigatório'}</span></div><label className="search-box"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar produto ou código"/></label><div className="sell-layout"><div className="catalog-grid">{list.map(p=><button key={p.id} disabled={(stock.get(p.id)||0)<=0} onClick={()=>add(p)}><Boxes size={20}/><b>{p.name}</b><span>{money(Number(p.sale_price))}</span><small>Estoque: {(stock.get(p.id)||0).toLocaleString('pt-BR')}</small></button>)}</div><aside className="cart"><h3>Conta</h3>{cart.length===0?<p>Toque em um produto para adicionar.</p>:cart.map(i=><div className="cart-row" key={i.product.id}><div><b>{i.product.name}</b><span>{money(Number(i.product.sale_price))}</span></div><div className="qty"><button onClick={()=>qty(i.product.id,-1)}>-</button><span>{i.quantity}</span><button onClick={()=>qty(i.product.id,1)}>+</button></div></div>)}<div className="cart-total"><span>Total</span><strong>{money(total)}</strong></div><select value={payment} onChange={e=>setPayment(e.target.value)}><option value="pix">PIX</option><option value="cash">Dinheiro</option><option value="debit">Débito</option><option value="credit">Crédito</option><option value="credit_book">Fiado</option></select><button className="btn-outline" disabled={!cart.length} onClick={share}><MessageCircle size={17}/> Enviar conta no WhatsApp</button><button className="btn-orange" disabled={!cart.length||loading} onClick={finish}>{loading?'Finalizando...':'Finalizar venda'}</button></aside></div></section>
}

function CashView({orgId,storeId,userId,cash,enabled,onChange,setMessage}:{orgId:string;storeId:string|null;userId:string;cash:any;enabled:boolean;onChange:()=>void;setMessage:(v:string)=>void}){const [opening,setOpening]=useState('0');const [counted,setCounted]=useState('0');async function open(){if(!enabled||!storeId)return;const r=await supabase.from('srp_cash_registers').insert({organization_id:orgId,store_id:storeId,opened_by:userId,opening_amount:Number(opening),status:'open'});setMessage(r.error?r.error.message:'Caixa aberto.');if(!r.error)onChange()}async function close(){if(!enabled||!cash)return;const r=await supabase.from('srp_cash_registers').update({status:'closed',closed_at:new Date().toISOString(),counted_amount:Number(counted)}).eq('id',cash.id);setMessage(r.error?r.error.message:'Caixa fechado.');if(!r.error)onChange()}return <section className="workspace-section"><div className="workspace-title"><div><span className="eyebrow">Financeiro diário</span><h2>Caixa</h2></div></div>{cash?<div className="cash-card"><WalletCards/><h3>Caixa aberto</h3><p>Aberto em {new Date(cash.opened_at).toLocaleString('pt-BR')}</p><strong>Fundo: {money(Number(cash.opening_amount))}</strong>{enabled&&<><input type="number" step="0.01" value={counted} onChange={e=>setCounted(e.target.value)} placeholder="Valor contado"/><button className="btn-dark" onClick={close}>Fechar caixa</button></>}</div>:<div className="cash-card"><WalletCards/><h3>Caixa fechado</h3>{enabled?<><input type="number" step="0.01" value={opening} onChange={e=>setOpening(e.target.value)} placeholder="Fundo de troco"/><button className="btn-orange" onClick={open}>Abrir caixa</button></>:<p>Seu perfil permite apenas consulta.</p>}</div>}</section>}

function MoreView({orgId,role,brand,editable,onChange,setMessage}:{orgId:string;role:Role;brand:Brand;editable:boolean;onChange:()=>void;setMessage:(v:string)=>void}){const file=useRef<HTMLInputElement>(null);const [name,setName]=useState(brand.name);const [color,setColor]=useState(brand.primary_color||'#F47A20');useEffect(()=>{setName(brand.name);setColor(brand.primary_color||'#F47A20')},[brand]);async function save(){const r=await supabase.from('srp_organizations').update({name,primary_color:color}).eq('id',orgId);setMessage(r.error?r.error.message:'Identidade atualizada.');if(!r.error)onChange()}async function upload(files:FileList|null){const f=files?.[0];if(!f)return;const ext=f.name.split('.').pop()||'png';const path=`${orgId}/logo-${Date.now()}.${ext}`;const up=await supabase.storage.from('srp-logos').upload(path,f,{upsert:true});if(up.error)return setMessage(up.error.message);const {data}=supabase.storage.from('srp-logos').getPublicUrl(path);const r=await supabase.from('srp_organizations').update({logo_url:data.publicUrl}).eq('id',orgId);setMessage(r.error?r.error.message:'Logo atualizada.');if(!r.error)onChange()}return <section className="workspace-section"><div className="workspace-title"><div><span className="eyebrow">Configurações</span><h2>Mais</h2></div><span className="role-chip">Perfil: {role}</span></div><div className="more-grid"><article><UserRound/><h3>Clientes / Fiado</h3><p>Cadastre clientes e acompanhe contas pendentes.</p></article><article><Settings/><h3>Usuários e permissões</h3><p>Perfis separados para gestão, caixa, estoque e consulta.</p></article><article><Store/><h3>Sua marca</h3><p>Logo e cor do seu negócio no app e nos comprovantes.</p></article></div>{editable&&<div className="brand-settings"><h3>Personalização</h3><div className="brand-preview">{brand.logo_url?<img src={brand.logo_url} alt={brand.name}/>:<div className="brand-mark">SP</div>}<b>{name}</b></div><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do negócio"/><label>Cor principal <input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><input ref={file} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files)}/><div className="row-actions"><button className="btn-outline" onClick={()=>file.current?.click()}>Trocar logo</button><button className="btn-orange" onClick={save}>Salvar identidade</button></div></div>}</section>}

function ReceiptModal({receipt,onClose}:{receipt:Receipt;onClose:()=>void}){const text=`${receipt.brand.name}\n${receipt.items.map(i=>`${i.quantity}x ${i.product.name} - ${money(i.quantity*Number(i.product.sale_price))}`).join('\n')}\nTOTAL: ${money(receipt.total)}\nPagamento: ${receipt.payment}`;function share(){window.open(`https://api.whatsapp.com/send?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer')}function save(){const canvas=document.createElement('canvas');canvas.width=720;canvas.height=Math.max(520,280+receipt.items.length*44);const c=canvas.getContext('2d');if(!c)return;c.fillStyle='#fff';c.fillRect(0,0,canvas.width,canvas.height);c.fillStyle=receipt.brand.primary_color||'#F47A20';c.fillRect(0,0,canvas.width,90);c.fillStyle='#fff';c.font='bold 32px Arial';c.fillText(receipt.brand.name,38,56);c.fillStyle='#20242A';c.font='bold 26px Arial';c.fillText('CONTA',38,142);c.font='20px Arial';let y=195;for(const i of receipt.items){c.fillText(`${i.quantity}x ${i.product.name}`,38,y);c.textAlign='right';c.fillText(money(i.quantity*Number(i.product.sale_price)),680,y);c.textAlign='left';y+=42}c.font='bold 28px Arial';c.fillText(`TOTAL: ${money(receipt.total)}`,38,y+28);canvas.toBlob(b=>{if(!b)return;const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`conta-${receipt.saleId||Date.now()}.png`;a.click();URL.revokeObjectURL(a.href)},'image/png')}return <div className="modal-backdrop"><div className="receipt-modal"><button className="modal-close" onClick={onClose}><X/></button><div className="receipt-brand">{receipt.brand.logo_url?<img src={receipt.brand.logo_url} alt={receipt.brand.name}/>:<div className="brand-mark">SP</div>}<h2>{receipt.brand.name}</h2></div>{receipt.items.map(i=><div className="summary-row" key={i.product.id}><span>{i.quantity}x {i.product.name}</span><strong>{money(i.quantity*Number(i.product.sale_price))}</strong></div>)}<div className="receipt-total"><span>Total</span><strong>{money(receipt.total)}</strong></div><button className="btn-orange" onClick={share}><MessageCircle size={17}/> Enviar por WhatsApp</button><button className="btn-outline" onClick={save}><Download size={17}/> Salvar imagem</button></div></div>}
