import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"https://meuespetinho.gritnews.com.br","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
async function adminClient(req:Request){const auth=req.headers.get('Authorization');if(!auth)throw new Error('unauthorized');const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);const{data:{user}}=await sb.auth.getUser(auth.replace('Bearer ',''));if(!user)throw new Error('unauthorized');const{data:admin}=await sb.from('admin_users').select('active').eq('user_id',user.id).maybeSingle();if(!admin?.active)throw new Error('forbidden');return{sb,user}}
async function secret(sb:any,name:string,value:string){const r=await sb.rpc('platform_secret_set',{secret_name:name,secret_value:value});if(r.error)throw new Error(r.error.message)}
async function googleAccessToken(clientId:string,clientSecret:string,refreshToken:string){const body=new URLSearchParams({client_id:clientId,client_secret:clientSecret,refresh_token:refreshToken,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const d=await r.json();if(!r.ok||!d.access_token)throw new Error(d.error_description||d.error||'google_oauth_failed');return d.access_token as string}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'method_not_allowed'},405);try{const{sb,user}=await adminClient(req);const body=await req.json();const provider=String(body.provider||'');
 if(provider==='google_ads'){const clientId=String(body.client_id||'').trim(),clientSecret=String(body.client_secret||'').trim(),refreshToken=String(body.refresh_token||'').trim(),developerToken=String(body.developer_token||'').trim(),customerId=String(body.customer_id||'').replace(/\D/g,''),loginCustomerId=String(body.login_customer_id||'').replace(/\D/g,'');if(!clientId||!clientSecret||!refreshToken||!developerToken||!customerId)return json({error:'missing_google_credentials'},400);const access=await googleAccessToken(clientId,clientSecret,refreshToken);const headers:any={Authorization:`Bearer ${access}`,'developer-token':developerToken};if(loginCustomerId)headers['login-customer-id']=loginCustomerId;const probe=await fetch('https://googleads.googleapis.com/v25/customers:listAccessibleCustomers',{headers});const data=await probe.json();if(!probe.ok)return json({error:'google_ads_validation_failed',detail:data},400);await secret(sb,'GOOGLE_ADS_CLIENT_ID',clientId);await secret(sb,'GOOGLE_ADS_CLIENT_SECRET',clientSecret);await secret(sb,'GOOGLE_ADS_REFRESH_TOKEN',refreshToken);await secret(sb,'GOOGLE_ADS_DEVELOPER_TOKEN',developerToken);await secret(sb,'GOOGLE_ADS_CUSTOMER_ID',customerId);await secret(sb,'GOOGLE_ADS_LOGIN_CUSTOMER_ID',loginCustomerId);await sb.from('marketing_provider_connections').upsert({provider:'google_ads',status:'connected',account_id:customerId,account_name:`Google Ads ${customerId}`,connected_by:user.id,connected_at:new Date().toISOString(),last_error:null});return json({ok:true,provider:'google_ads',account_id:customerId,accessible_customers:data.resourceNames?.length||0})}
 if(provider==='meta_ads'){const accessToken=String(body.access_token||'').trim(),adAccountId=String(body.ad_account_id||'').replace(/^act_/,'').replace(/\D/g,'');if(!accessToken||!adAccountId)return json({error:'missing_meta_credentials'},400);const probe=await fetch(`https://graph.facebook.com/v23.0/act_${adAccountId}?fields=id,name,account_status&access_token=${encodeURIComponent(accessToken)}`);const data=await probe.json();if(!probe.ok||data.error)return json({error:'meta_ads_validation_failed',detail:data.error||data},400);await secret(sb,'META_ADS_ACCESS_TOKEN',accessToken);await secret(sb,'META_ADS_ACCOUNT_ID',adAccountId);await sb.from('marketing_provider_connections').upsert({provider:'meta_ads',status:'connected',account_id:adAccountId,account_name:data.name||`Meta Ads ${adAccountId}`,connected_by:user.id,connected_at:new Date().toISOString(),last_error:null});return json({ok:true,provider:'meta_ads',account_id:adAccountId,account_name:data.name||null})}
 return json({error:'invalid_provider'},400)}catch(e){const m=e instanceof Error?e.message:String(e);return json({error:m},m==='unauthorized'?401:m==='forbidden'?403:500)}});
