import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"https://meuespetinho.gritnews.com.br","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const today=()=>new Date().toISOString().slice(0,10);const num=(v:any)=>{const n=Number(v||0);return Number.isFinite(n)?n:0};
async function getSecret(sb:any,name:string){const r=await sb.rpc('platform_secret_get',{secret_name:name});return r.error?'':String(r.data||'')}
async function googleAccessToken(sb:any){const cid=await getSecret(sb,'GOOGLE_ADS_CLIENT_ID'),sec=await getSecret(sb,'GOOGLE_ADS_CLIENT_SECRET'),ref=await getSecret(sb,'GOOGLE_ADS_REFRESH_TOKEN');if(!cid||!sec||!ref)throw new Error('google_ads_not_configured');const b=new URLSearchParams({client_id:cid,client_secret:sec,refresh_token:ref,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:b});const d=await r.json();if(!r.ok||!d.access_token)throw new Error('google_oauth_failed');return String(d.access_token)}
function actionValue(items:any[],names:string[]){return(items||[]).filter(x=>names.includes(String(x.action_type||''))).reduce((s,x)=>s+num(x.value),0)}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'method_not_allowed'},405);const auth=req.headers.get('Authorization');if(!auth)return json({error:'unauthorized'},401);const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);const{data:{user}}=await sb.auth.getUser(auth.replace('Bearer ',''));if(!user)return json({error:'unauthorized'},401);const{data:admin}=await sb.from('admin_users').select('active').eq('user_id',user.id).maybeSingle();if(!admin?.active)return json({error:'forbidden'},403);
 try{const body=await req.json().catch(()=>({}));const apply=Boolean(body?.apply_optimization);const results:any[]=[];const{data:campaigns,error}=await sb.from('marketing_campaigns').select('*').eq('provider_sync_enabled',true).not('external_campaign_id','is',null);if(error)throw error;
 const google=(campaigns||[]).filter((c:any)=>['google_search','google_display','youtube'].includes(c.platform));if(google.length){try{const token=await googleAccessToken(sb),dev=await getSecret(sb,'GOOGLE_ADS_DEVELOPER_TOKEN'),customer=await getSecret(sb,'GOOGLE_ADS_CUSTOMER_ID'),login=await getSecret(sb,'GOOGLE_ADS_LOGIN_CUSTOMER_ID');const headers:any={Authorization:`Bearer ${token}`,'developer-token':dev,'Content-Type':'application/json'};if(login)headers['login-customer-id']=login;for(const c of google){const id=String(c.external_campaign_id).replace(/\D/g,'');const q=`SELECT segments.date, campaign.id, metrics.cost_micros, metrics.impressions, metrics.clicks, metrics.conversions, metrics.conversions_value FROM campaign WHERE campaign.id = ${id} AND segments.date DURING LAST_7_DAYS`;const r=await fetch(`https://googleads.googleapis.com/v25/customers/${customer}/googleAds:searchStream`,{method:'POST',headers,body:JSON.stringify({query:q})});const d=await r.json();if(!r.ok){results.push({campaign:c.id,provider:'google_ads',ok:false});continue}for(const batch of(Array.isArray(d)?d:[]))for(const row of(batch.results||[])){const m=row.metrics||{};await sb.from('marketing_campaign_metrics').upsert({campaign_id:c.id,metric_date:row.segments?.date||today(),spend:num(m.costMicros)/1e6,impressions:num(m.impressions),clicks:num(m.clicks),provider_conversions:num(m.conversions),provider_conversion_value:num(m.conversionsValue),source:'google_ads',synced_at:new Date().toISOString()},{onConflict:'campaign_id,metric_date,source'})}results.push({campaign:c.id,provider:'google_ads',ok:true})}await sb.from('marketing_provider_connections').update({last_sync_at:new Date().toISOString(),status:'connected',last_error:null}).eq('provider','google_ads')}catch(e){const m=e instanceof Error?e.message:String(e);await sb.from('marketing_provider_connections').update({status:'error',last_error:m}).eq('provider','google_ads');results.push({provider:'google_ads',ok:false,error:m})}}
 const meta=(campaigns||[]).filter((c:any)=>['meta','facebook','instagram'].includes(c.platform));if(meta.length){try{const token=await getSecret(sb,'META_ADS_ACCESS_TOKEN');if(!token)throw new Error('meta_ads_not_configured');const since=new Date(Date.now()-6*86400000).toISOString().slice(0,10),until=today();for(const c of meta){const fields='campaign_id,date_start,spend,impressions,clicks,actions,action_values',tr=encodeURIComponent(JSON.stringify({since,until}));const r=await fetch(`https://graph.facebook.com/v23.0/${c.external_campaign_id}/insights?fields=${fields}&time_increment=1&time_range=${tr}&access_token=${encodeURIComponent(token)}`);const d=await r.json();if(!r.ok||d.error){results.push({campaign:c.id,provider:'meta_ads',ok:false});continue}for(const row of(d.data||[])){const names=['purchase','offsite_conversion.fb_pixel_purchase','subscribe','offsite_conversion.fb_pixel_subscribe'],subs=actionValue(row.actions||[],names),revenue=actionValue(row.action_values||[],names);await sb.from('marketing_campaign_metrics').upsert({campaign_id:c.id,metric_date:row.date_start||today(),spend:num(row.spend),impressions:num(row.impressions),clicks:num(row.clicks),subscriptions:Math.round(subs),revenue,provider_conversions:subs,provider_conversion_value:revenue,source:'meta_ads',synced_at:new Date().toISOString()},{onConflict:'campaign_id,metric_date,source'})}results.push({campaign:c.id,provider:'meta_ads',ok:true})}await sb.from('marketing_provider_connections').update({last_sync_at:new Date().toISOString(),status:'connected',last_error:null}).eq('provider','meta_ads')}catch(e){const m=e instanceof Error?e.message:String(e);await sb.from('marketing_provider_connections').update({status:'error',last_error:m}).eq('provider','meta_ads');results.push({provider:'meta_ads',ok:false,error:m})}}
 const rpc=await sb.rpc('evaluate_growth_campaigns',{p_apply:apply});return json({ok:true,synced:results,optimization:rpc.data||null,optimization_error:rpc.error?.message||null})}catch(e){return json({error:'sync_failed',detail:e instanceof Error?e.message:String(e)},500)}});
