-- SEO Growth foundation: page inventory + Search Console-ready metrics.
create table if not exists public.seo_pages (
  id uuid primary key default gen_random_uuid(),
  path text not null unique,
  page_type text not null check (page_type in ('landing','guide','hub')),
  cluster text not null,
  primary_keyword text not null,
  intent text not null check (intent in ('bofu','mofu','tofu')),
  status text not null default 'active' check (status in ('active','draft','archived')),
  priority smallint not null default 3 check (priority between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seo_search_metrics (
  id bigint generated by default as identity primary key,
  metric_date date not null,
  path text not null,
  query text not null default '',
  impressions integer not null default 0,
  clicks integer not null default 0,
  ctr numeric(9,6) not null default 0,
  position numeric(9,3),
  source text not null default 'search_console',
  created_at timestamptz not null default now(),
  unique(metric_date,path,query,source)
);

alter table public.seo_pages enable row level security;
alter table public.seo_search_metrics enable row level security;

create policy "seo_pages_admin_read" on public.seo_pages for select to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.active=true));
create policy "seo_search_metrics_admin_read" on public.seo_search_metrics for select to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.active=true));

insert into public.seo_pages(path,page_type,cluster,primary_keyword,intent,priority) values
('/sistema-para-espetinho','landing','pdv','sistema para espetinho','bofu',5),
('/pdv-para-espetinho','landing','pdv','pdv para espetinho','bofu',5),
('/comanda-digital-para-espetinho','landing','comandas','comanda digital para espetinho','bofu',5),
('/controle-de-caixa-para-espetinho','landing','financeiro','controle de caixa para espetinho','bofu',4),
('/controle-de-fiado','landing','financeiro','controle de fiado','bofu',4),
('/controle-de-estoque-para-bar','landing','estoque','controle de estoque para bar','bofu',4),
('/relatorios-de-vendas-para-bar','landing','gestao','relatorios de vendas para bar','bofu',4),
('/guias','hub','conteudo','guias para bar e espetinho','mofu',3),
('/guias/como-controlar-fiado-no-bar','guide','financeiro','como controlar fiado no bar','mofu',4),
('/guias/como-organizar-comandas-de-mesa','guide','comandas','como organizar comandas de mesa','mofu',4),
('/guias/como-fazer-fechamento-de-caixa','guide','financeiro','como fazer fechamento de caixa','mofu',4),
('/guias/como-controlar-estoque-de-bebidas','guide','estoque','como controlar estoque de bebidas','mofu',4),
('/guias/como-administrar-espetinho-pelo-celular','guide','pdv','como administrar espetinho pelo celular','mofu',4),
('/guias/como-calcular-ticket-medio','guide','gestao','como calcular ticket medio','tofu',3)
on conflict(path) do update set cluster=excluded.cluster,primary_keyword=excluded.primary_keyword,intent=excluded.intent,priority=excluded.priority,updated_at=now();
