#!/usr/bin/env bash
set -euo pipefail
: "${SUPABASE_PROJECT_REF:?Defina SUPABASE_PROJECT_REF}"
: "${MERCADO_PAGO_ACCESS_TOKEN:?Defina MERCADO_PAGO_ACCESS_TOKEN}"
: "${MERCADO_PAGO_WEBHOOK_SECRET:?Defina MERCADO_PAGO_WEBHOOK_SECRET}"
: "${APP_BASE_URL:?Defina APP_BASE_URL}"
ACTIVATION_AMOUNT="${ACTIVATION_AMOUNT:-199}"
MONTHLY_AMOUNT="${MONTHLY_AMOUNT:-89}"
MERCADO_PAGO_MODE="${MERCADO_PAGO_MODE:-test}"

supabase secrets set --project-ref "$SUPABASE_PROJECT_REF" \
  MERCADO_PAGO_ACCESS_TOKEN="$MERCADO_PAGO_ACCESS_TOKEN" \
  MERCADO_PAGO_WEBHOOK_SECRET="$MERCADO_PAGO_WEBHOOK_SECRET" \
  MERCADO_PAGO_MODE="$MERCADO_PAGO_MODE" \
  APP_BASE_URL="$APP_BASE_URL" \
  ACTIVATION_AMOUNT="$ACTIVATION_AMOUNT" \
  MONTHLY_AMOUNT="$MONTHLY_AMOUNT"

echo "Secrets configurados no Supabase. Nenhum valor foi gravado no repositório."
